import { randomUUID } from "node:crypto";
import { builderAttestedAcceptanceV1, quoteDispositionV1 } from "@jobguard/core";
import type { AuditEventInput } from "./audit.js";
import type { CommandMutation, ConsequentialCommand } from "./commands.js";
import type { TenantTransaction } from "./tenant-context.js";
import type { Pool } from "pg";
import { DEMO_MEMBERSHIP_ID } from "./demo-seed.js";
import { UserCommandDispatcher } from "./commands.js";
import { withTenant, type VerifiedTenantContext } from "./tenant-context.js";

const domainAudit=(command:ConsequentialCommand,eventType:string,eventId:string,documentId:string,hash:string):AuditEventInput=>({id:randomUUID(),version:"audit.v1",actorRef:`membership:${command.actorMembershipId}`,eventType,subjectType:"quote_document",subjectRef:documentId,payload:{references:{acceptanceEventId:eventId},hashes:{documentHash:hash},classifications:{action:"commercial"}}});

export class RecordBuilderAcceptanceMutation implements CommandMutation<Record<string,unknown>> {
  private eventId="";
  constructor(private readonly tenantId:string,private readonly raw:unknown){}
  async mutate(db:TenantTransaction,command:ConsequentialCommand){const input=builderAttestedAcceptanceV1.parse(this.raw);this.eventId=randomUUID();if(command.action.actionType!=="quote.acceptance.attest"||command.action.contentHash!==input.documentHash||command.action.aggregateRevision!==input.documentVersion||command.action.amountPence!==input.acceptedTotalPence||command.action.currency!=="GBP"||command.action.policyVersion!=="builder-attestation.v1")throw new Error("EXACT_ACCEPTANCE_AUTHORIZATION_MISMATCH");const result=(await db.$client.query(`SELECT * FROM app.record_builder_attested_acceptance($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[this.tenantId,input.acceptanceId,this.eventId,input.jobId,input.documentId,input.documentVersion,input.documentHash,input.acceptedTotalPence,input.expectedJobRevision,command.actorMembershipId,input.statedCustomerName,input.statedMethod,input.acceptedAt,input.evidenceId])).rows[0] as Record<string,unknown>;return{acceptanceId:input.acceptanceId,eventId:this.eventId,jobId:input.jobId,documentId:input.documentId,documentVersion:input.documentVersion,documentHash:input.documentHash,acceptedTotalPence:input.acceptedTotalPence,acceptanceKind:result.acceptance_kind,state:"accepted"};}
  auditEvents(_result:Record<string,unknown>,command:ConsequentialCommand){const input=builderAttestedAcceptanceV1.parse(this.raw);return[domainAudit(command,"quote.acceptance.attested",this.eventId,input.documentId,input.documentHash)];}
}

export class RecordQuoteDispositionMutation implements CommandMutation<Record<string,unknown>> {
  constructor(private readonly tenantId:string,private readonly raw:unknown){}
  async mutate(db:TenantTransaction,command:ConsequentialCommand){const input=quoteDispositionV1.parse(this.raw);if(command.action.actionType!==`quote.${input.kind}`||command.action.contentHash!==input.documentHash||command.action.aggregateRevision!==input.documentVersion||command.action.amountPence!==null||command.action.currency!==null)throw new Error("EXACT_DISPOSITION_AUTHORIZATION_MISMATCH");await db.$client.query(`SELECT * FROM app.record_quote_disposition($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[this.tenantId,input.eventId,input.jobId,input.documentId,input.documentVersion,input.documentHash,input.expectedJobRevision,command.actorMembershipId,input.kind,input.occurredAt]);return{eventId:input.eventId,jobId:input.jobId,documentId:input.documentId,kind:input.kind,state:input.kind==="declined"?"lost":"quoting"};}
  auditEvents(_result:Record<string,unknown>,command:ConsequentialCommand){const input=quoteDispositionV1.parse(this.raw);return[domainAudit(command,`quote.${input.kind}`,input.eventId,input.documentId,input.documentHash)];}
}

export class QuoteAcceptanceRepository {
  constructor(private readonly pool:Pool){}
  async view(context:VerifiedTenantContext,jobId:string){return withTenant(this.pool,context,async db=>{const job=(await db.$client.query<any>(`SELECT status,revision,accepted_quote_version_id FROM app.job WHERE tenant_id=$1 AND id=$2`,[context.tenantId,jobId])).rows[0];if(!job)throw new Error("NOT_FOUND");const document=(await db.$client.query<any>(`SELECT id,document_version,content_hash,(snapshot->>'netPence')::bigint net_pence,(snapshot->>'totalPence')::bigint total_pence FROM app.quote_document_version WHERE tenant_id=$1 AND job_id=$2 ORDER BY document_version DESC LIMIT 1`,[context.tenantId,jobId])).rows[0]??null;const acceptance=job.accepted_quote_version_id?(await db.$client.query<any>(`SELECT a.*,(d.snapshot->>'netPence')::bigint net_pence FROM app.quote_acceptance a JOIN app.quote_document_version d ON(d.tenant_id,d.id)=(a.tenant_id,a.document_id) WHERE a.tenant_id=$1 AND a.job_id=$2 AND a.document_id=$3`,[context.tenantId,jobId,job.accepted_quote_version_id])).rows[0]??null:null;const events=(await db.$client.query<any>(`SELECT id,kind,document_version,document_hash,occurred_at FROM app.acceptance_event WHERE tenant_id=$1 AND job_id=$2 ORDER BY recorded_at,id`,[context.tenantId,jobId])).rows;return{version:1 as const,environment:"synthetic_demo" as const,jobId,jobStatus:job.status as string,jobRevision:Number(job.revision),currentDocument:document?{id:document.id,version:document.document_version,hash:document.content_hash,netPence:Number(document.net_pence),totalPence:Number(document.total_pence)}:null,activeAcceptance:acceptance?{id:acceptance.id,documentId:acceptance.document_id,documentVersion:acceptance.document_version,documentHash:acceptance.document_hash,netPence:Number(acceptance.net_pence),totalPence:Number(acceptance.accepted_total_pence),actor:"A Builder Ltd (builder)",acceptedAt:new Date(acceptance.accepted_at).toISOString(),method:acceptance.stated_method,statedCustomerName:acceptance.stated_customer_name,sourceEvidence:acceptance.evidence_id?`Evidence ${acceptance.evidence_id}`:"No supporting evidence attached"}:null,events:events.map((e:any)=>({id:e.id,kind:e.kind,documentVersion:e.document_version,documentHash:e.document_hash,occurredAt:new Date(e.occurred_at).toISOString(),actor:"A Builder Ltd (builder)"})),effects:{platformObligations:0 as const,settlements:0 as const,recoveryFees:0 as const}};});}
  async accept(context:VerifiedTenantContext,jobId:string,input:{commandId:string;documentId:string;documentHash:string;documentVersion:number;statedCustomerName:string;statedMethod:"verbal"|"email"|"message"|"signed-paper";acceptedAt:string}){const view=await this.view(context,jobId),d=view.currentDocument;if(!d||d.id!==input.documentId||d.hash!==input.documentHash||d.version!==input.documentVersion)throw new Error("STALE_ACCEPTANCE");await new UserCommandDispatcher(this.pool).dispatch(context,{version:"command.v1",commandId:input.commandId,commandType:"quote.acceptance.attest",semanticKey:`practice-accept:${input.documentId}`,actorMembershipId:DEMO_MEMBERSHIP_ID,subjectType:"quote_document",subjectRef:input.documentId,action:{actionType:"quote.acceptance.attest",recipient:input.statedCustomerName,contentHash:input.documentHash,aggregateRevision:input.documentVersion,amountPence:d.totalPence,currency:"GBP",policyVersion:"builder-attestation.v1",expiresAt:new Date("2099-01-01T00:00:00.000Z")}},new RecordBuilderAcceptanceMutation(context.tenantId,{version:"quote-acceptance.v1",acceptanceId:randomUUID(),jobId,documentId:input.documentId,documentVersion:input.documentVersion,documentHash:input.documentHash,expectedJobRevision:view.jobRevision,acceptedTotalPence:d.totalPence,acceptedAt:input.acceptedAt,statedCustomerName:input.statedCustomerName,statedMethod:input.statedMethod,evidenceId:null}));return this.view(context,jobId);}
  async disposition(context:VerifiedTenantContext,jobId:string,input:{commandId:string;documentId:string;documentHash:string;documentVersion:number;kind:"declined"|"superseded"|"acceptance_cancelled";occurredAt:string}){const view=await this.view(context,jobId);await new UserCommandDispatcher(this.pool).dispatch(context,{version:"command.v1",commandId:input.commandId,commandType:`quote.${input.kind}`,semanticKey:`${input.kind}:${input.documentId}`,actorMembershipId:DEMO_MEMBERSHIP_ID,subjectType:"quote_document",subjectRef:input.documentId,action:{actionType:`quote.${input.kind}`,recipient:null,contentHash:input.documentHash,aggregateRevision:input.documentVersion,amountPence:null,currency:null,policyVersion:"quote-disposition.v1",expiresAt:new Date("2099-01-01T00:00:00.000Z")}},new RecordQuoteDispositionMutation(context.tenantId,{version:"quote-disposition.v1",eventId:randomUUID(),jobId,documentId:input.documentId,documentVersion:input.documentVersion,documentHash:input.documentHash,expectedJobRevision:view.jobRevision,kind:input.kind,occurredAt:input.occurredAt}));return this.view(context,jobId);}
}
