import { randomUUID } from "node:crypto";
import { ACTIVATION_POLICY_VERSION, ILLUSTRATIVE_BASE_PRINCIPAL_PENCE, PILOT_NO_CHARGE_TERMS, SYNTHETIC_DEMO_TERMS, assertSwitchLiveTerms, money, recoveryCap, simulatedSettlementV1, switchLiveV1 } from "@jobguard/core";
import type { AuditEventInput } from "./audit.js";
import type { CommandMutation, ConsequentialCommand } from "./commands.js";
import type { TenantTransaction } from "./tenant-context.js";
import type { Pool } from "pg";
import { UserCommandDispatcher } from "./commands.js";
import { DEMO_MEMBERSHIP_ID } from "./demo-seed.js";
import { withTenant, type VerifiedTenantContext } from "./tenant-context.js";

type DeploymentMode = "pilot_no_charge" | "synthetic_demo" | "production_billing";
const audit=(command:ConsequentialCommand,eventType:string,subjectRef:string,references:Record<string,string>,hash?:string):AuditEventInput=>({id:randomUUID(),version:"audit.v1",actorRef:`membership:${command.actorMembershipId}`,eventType,subjectType:"job",subjectRef,payload:{references,...(hash?{hashes:{acceptedDocumentHash:hash}}:{}),classifications:{action:"commercial"}}});

export class SwitchJobLiveMutation implements CommandMutation<Record<string,unknown>> {
  constructor(private readonly tenantId:string,private readonly deploymentMode:Exclude<DeploymentMode,"production_billing">,private readonly raw:unknown){}
  async mutate(db:TenantTransaction,command:ConsequentialCommand){const input=switchLiveV1.parse(this.raw);assertSwitchLiveTerms(input);
    if(input.mode!==this.deploymentMode)throw new Error("DEPLOYMENT_MODE_MISMATCH");
    const expectedAmount=input.mode==="synthetic_demo"?7900:null;
    if(command.action.actionType!=="job.switch_live"||command.subjectType!=="job"||command.subjectRef!==input.jobId||command.action.contentHash!==input.acceptedDocumentHash||command.action.aggregateRevision!==input.acceptedDocumentVersion||command.action.amountPence!==expectedAmount||command.action.currency!==(expectedAmount===null?null:"GBP")||command.action.policyVersion!==input.activationTermsVersion)throw new Error("EXACT_ACTIVATION_AUTHORIZATION_MISMATCH");
    await db.$client.query(`SELECT * FROM app.switch_job_live($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,[this.tenantId,input.activationId,input.capSnapshotId,input.syntheticObligationId,input.jobId,input.acceptedDocumentId,input.acceptedDocumentVersion,input.acceptedDocumentHash,input.expectedJobRevision,input.acceptedNetValuePence,input.recoveryCapPence,input.mode,input.activationTermsVersion,input.feePolicyVersion,command.actorMembershipId,input.activatedAt]);
    return{activationId:input.activationId,capSnapshotId:input.capSnapshotId,syntheticObligationId:input.syntheticObligationId,jobId:input.jobId,state:"live",mode:input.mode,acceptedNetValuePence:input.acceptedNetValuePence,recoveryCapPence:input.recoveryCapPence,label:input.mode==="pilot_no_charge"?"no charge":"illustrative only"};}
  auditEvents(_result:Record<string,unknown>,command:ConsequentialCommand){const input=switchLiveV1.parse(this.raw);return[audit(command,"job.switched_live",input.jobId,{activationId:input.activationId,capSnapshotId:input.capSnapshotId,acceptedDocumentId:input.acceptedDocumentId},input.acceptedDocumentHash)];}
}

export class RecordSimulatedSettlementMutation implements CommandMutation<Record<string,unknown>> {
  constructor(private readonly tenantId:string,private readonly deploymentMode:DeploymentMode,private readonly raw:unknown){}
  async mutate(db:TenantTransaction,command:ConsequentialCommand){if(this.deploymentMode!=="synthetic_demo")throw new Error("SIMULATED_SETTLEMENT_ENVIRONMENT_FORBIDDEN");const input=simulatedSettlementV1.parse(this.raw);
    if(command.action.actionType!=="synthetic_obligation.simulate_settlement"||command.subjectRef!==input.obligationId||command.action.amountPence!==input.amountPence||command.action.currency!=="GBP"||command.action.policyVersion!=="synthetic_demo_illustrative.v1")throw new Error("EXACT_SIMULATION_AUTHORIZATION_MISMATCH");
    await db.$client.query(`SELECT * FROM app.record_simulated_settlement($1,$2,$3,$4,$5,$6)`,[this.tenantId,input.settlementId,input.obligationId,input.providerEventId,input.amountPence,input.simulatedAt]);return{settlementId:input.settlementId,obligationId:input.obligationId,label:"simulated — not collected"};}
  auditEvents(_result:Record<string,unknown>,command:ConsequentialCommand){const input=simulatedSettlementV1.parse(this.raw);return[audit(command,"synthetic_obligation.simulated_settlement",input.obligationId,{settlementId:input.settlementId,providerEventId:input.providerEventId})];}
}

export type PracticeActivationView={version:1;environment:"synthetic_demo";jobId:string;jobStatus:string;jobRevision:number;activation:null|{id:string;acceptedDocumentId:string;acceptedDocumentVersion:number;acceptedDocumentHash:string;acceptedNetPence:number;recoveryCapPence:number;policyVersion:string;scenario:"no_charge"|"simulated_base_obligation";baseStatus:string;baseCreditPence:0;activatedAt:string};effects:{activations:number;capSnapshots:number;simulatedObligations:number;settlements:number;platformJournals:number;realExternalActions:0}};

/** Synthetic web facade. The server, never the browser, selects deployment mode and snapshot facts. */
export class PracticeActivationRepository{
  constructor(private readonly pool:Pool){}
  async view(context:VerifiedTenantContext,jobId:string):Promise<PracticeActivationView>{return withTenant(this.pool,context,async db=>{const job=(await db.$client.query<any>(`SELECT status,revision FROM app.job WHERE tenant_id=$1 AND id=$2`,[context.tenantId,jobId])).rows[0];if(!job)throw new Error("NOT_FOUND");const row=(await db.$client.query<any>(`SELECT a.id,a.accepted_document_id,a.accepted_document_version,a.accepted_document_hash,a.mode,a.fee_policy_version,a.activated_at,c.accepted_net_value_pence,c.recovery_cap_pence,o.principal_pence,(SELECT count(*)::int FROM app.simulated_settlement_event s WHERE s.tenant_id=a.tenant_id AND s.obligation_id=o.id) settlements FROM app.job_activation a JOIN app.cap_snapshot c ON(c.tenant_id,c.activation_id)=(a.tenant_id,a.id) LEFT JOIN app.synthetic_obligation o ON(o.tenant_id,o.activation_id)=(a.tenant_id,a.id) WHERE a.tenant_id=$1 AND a.job_id=$2`,[context.tenantId,jobId])).rows[0]??null;const counts=(await db.$client.query<any>(`SELECT (SELECT count(*)::int FROM app.job_activation WHERE tenant_id=$1 AND job_id=$2) activations,(SELECT count(*)::int FROM app.cap_snapshot WHERE tenant_id=$1 AND job_id=$2) cap_snapshots,(SELECT count(*)::int FROM app.synthetic_obligation WHERE tenant_id=$1 AND job_id=$2) simulated_obligations,(SELECT count(*)::int FROM app.simulated_settlement_event WHERE tenant_id=$1 AND job_id=$2) settlements,(SELECT count(*)::int FROM app.journal WHERE tenant_id=$1) platform_journals`,[context.tenantId,jobId])).rows[0];return{version:1,environment:"synthetic_demo",jobId,jobStatus:job.status,jobRevision:Number(job.revision),activation:row?{id:row.id,acceptedDocumentId:row.accepted_document_id,acceptedDocumentVersion:Number(row.accepted_document_version),acceptedDocumentHash:row.accepted_document_hash,acceptedNetPence:Number(row.accepted_net_value_pence),recoveryCapPence:Number(row.recovery_cap_pence),policyVersion:row.fee_policy_version,scenario:row.mode==="synthetic_demo"?"simulated_base_obligation":"no_charge",baseStatus:row.mode==="synthetic_demo"?"Simulated obligation £79.00 — unpaid":"No real charge",baseCreditPence:0,activatedAt:new Date(row.activated_at).toISOString()}:null,effects:{activations:Number(counts.activations),capSnapshots:Number(counts.cap_snapshots),simulatedObligations:Number(counts.simulated_obligations),settlements:Number(counts.settlements),platformJournals:Number(counts.platform_journals),realExternalActions:0}};});}
  async start(context:VerifiedTenantContext,jobId:string,input:{commandId:string;scenario:"no_charge"|"simulated_base_obligation"}){const current=await this.view(context,jobId);if(current.activation)return current;const accepted=await withTenant(this.pool,context,async db=>(await db.$client.query<any>(`SELECT j.status,j.revision,j.accepted_quote_version_id,d.document_version,d.content_hash,(d.snapshot->>'netPence')::bigint net_pence FROM app.job j LEFT JOIN app.quote_document_version d ON(d.tenant_id,d.id)=(j.tenant_id,j.accepted_quote_version_id) WHERE j.tenant_id=$1 AND j.id=$2`,[context.tenantId,jobId])).rows[0]);if(!accepted||accepted.status!=="accepted"||!accepted.accepted_quote_version_id)throw new Error("ACCEPTED_PRICED_QUOTE_REQUIRED");const mode=input.scenario==="simulated_base_obligation"?"synthetic_demo" as const:"pilot_no_charge" as const;const net=Number(accepted.net_pence),cap=recoveryCap(money(net)).pence,terms=mode==="synthetic_demo"?SYNTHETIC_DEMO_TERMS:PILOT_NO_CHARGE_TERMS;const activation={version:"switch-live.v1" as const,activationId:randomUUID(),capSnapshotId:randomUUID(),syntheticObligationId:mode==="synthetic_demo"?randomUUID():null,jobId,acceptedDocumentId:accepted.accepted_quote_version_id,acceptedDocumentVersion:Number(accepted.document_version),acceptedDocumentHash:accepted.content_hash,expectedJobRevision:Number(accepted.revision),acceptedNetValuePence:net,recoveryCapPence:cap,mode,activationTermsVersion:terms,feePolicyVersion:ACTIVATION_POLICY_VERSION,activatedAt:new Date()};try{await new UserCommandDispatcher(this.pool).dispatch(context,{version:"command.v1",commandId:input.commandId,commandType:"job.switch_live",semanticKey:`practice-start:${jobId}`,actorMembershipId:DEMO_MEMBERSHIP_ID,subjectType:"job",subjectRef:jobId,action:{actionType:"job.switch_live",recipient:null,contentHash:accepted.content_hash,aggregateRevision:Number(accepted.document_version),amountPence:mode==="synthetic_demo"?ILLUSTRATIVE_BASE_PRINCIPAL_PENCE:null,currency:mode==="synthetic_demo"?"GBP":null,policyVersion:terms,expiresAt:new Date("2099-01-01T00:00:00.000Z")}},new SwitchJobLiveMutation(context.tenantId,mode,activation));}catch(error){for(let attempt=0;attempt<20;attempt++){const winner=await this.view(context,jobId);if(winner.activation)return winner;await new Promise(resolve=>setTimeout(resolve,25));}throw error}return this.view(context,jobId);}
}
