import { randomUUID } from "node:crypto";
import type { Pool } from "pg";
import { DEMO_TENANT_ID } from "./demo-seed.js";
import { withTenant, type VerifiedTenantContext } from "./tenant-context.js";

export type RecoveryDemoScenario="missing_evidence"|"pending_money"|"manual_receipt"|"unapproved_eligibility"|"prevented"|"eligible";
export type RecoveryGuardView={jobId:string;scenario:RecoveryDemoScenario|null;reason:string;qualifies:boolean;additionalFeePence:number;approved:boolean;caseId:string|null;receiptId:string|null;evidenceId:string|null;allocationId:string|null;policyVersion:"reference_fee_policy_v1";environment:"synthetic_demo"};
const context={tenantId:DEMO_TENANT_ID} as VerifiedTenantContext;
const reasons:Record<RecoveryDemoScenario,string>={missing_evidence:"Finalized evidence is missing",pending_money:"The generated money event is still pending",manual_receipt:"A manual receipt is not bank-confirmed landing",unapproved_eligibility:"Eligibility has not been approved",prevented:"Prevented cases never generate a positive recovery fee",eligible:"All structural guards passed — inspect the authorized synthetic landing"};
export class RecoveryDemoRepository{
 constructor(private pool:Pool){}
 async select(jobId:string,commandId:string,scenario:RecoveryDemoScenario){await withTenant(this.pool,context,db=>db.$client.query("SELECT app.configure_recovery_demo($1,$2,$3)",[jobId,commandId,scenario]));return this.read(jobId)}
 async read(jobId:string):Promise<RecoveryGuardView>{return withTenant(this.pool,context,async db=>{const q=await db.$client.query<any>(`SELECT s.*,a.id allocation_id,d.liability_pence FROM app.recovery_demo_selection s LEFT JOIN app.landing_allocation a ON(a.tenant_id,a.job_id,a.case_id)=(s.tenant_id,s.job_id,s.case_id) LEFT JOIN app.recovery_fee_derivation d ON(d.tenant_id,d.source_allocation_id)=(a.tenant_id,a.id) WHERE s.tenant_id=$1 AND s.job_id=$2`,[DEMO_TENANT_ID,jobId]);if(!q.rowCount)return{jobId,scenario:null,reason:"Choose a generated scenario to inspect the structural guard",qualifies:false,additionalFeePence:0,approved:false,caseId:null,receiptId:null,evidenceId:null,allocationId:null,policyVersion:"reference_fee_policy_v1",environment:"synthetic_demo"};const x=q.rows[0],scenario=x.scenario as RecoveryDemoScenario;return{jobId,scenario,reason:reasons[scenario],qualifies:scenario==="eligible",additionalFeePence:Number(x.liability_pence??0),approved:Boolean(x.allocation_id),caseId:x.case_id,receiptId:x.receipt_id,evidenceId:x.evidence_id,allocationId:x.allocation_id,policyVersion:"reference_fee_policy_v1",environment:"synthetic_demo"}})}
 async approve(jobId:string,commandId:string){await withTenant(this.pool,context,async db=>{const q=await db.$client.query<any>("SELECT * FROM app.recovery_demo_selection WHERE tenant_id=$1 AND job_id=$2",[DEMO_TENANT_ID,jobId]);const x=q.rows[0];if(!x||x.scenario!=="eligible")throw new Error("RECOVERY_GUARD_DENIED");const existing=await db.$client.query("SELECT 1 FROM app.landing_allocation WHERE tenant_id=$1 AND job_id=$2 AND case_id=$3",[DEMO_TENANT_ID,jobId,x.case_id]);if(!existing.rowCount)await db.$client.query("SELECT app.approve_synthetic_landing($1::jsonb)",[JSON.stringify({version:"recovery.landing.approve.v1",commandId,allocationId:randomUUID(),derivationId:randomUUID(),journalId:randomUUID(),jobId,caseId:x.case_id,receiptId:x.receipt_id,evidenceId:x.evidence_id,eligibilityApprovalId:x.eligibility_approval_id,landingApprovalId:x.landing_approval_id,grossPence:18000,eligibleNetPence:15000,currency:"GBP",policyVersion:"reference_fee_policy_v1",expectedCaseRevision:0})]);});return this.read(jobId)}
}
