import { z } from "zod";

const partyV1=z.object({name:z.string().min(1).max(160),address:z.array(z.string().min(1).max(160)).min(1).max(8),email:z.string().email().max(320)}).strict();
export const quoteDocumentV1=z.object({schemaVersion:z.literal("quote-document.v1"),documentVersion:z.number().int().positive(),reference:z.string().min(1).max(80),quoteRevisionId:z.string().uuid(),currency:z.literal("GBP"),issuer:partyV1,customer:partyV1,lines:z.array(z.object({scopeItemId:z.string().uuid(),description:z.string().min(1).max(500),quantity:z.string().min(1).max(40),unit:z.string().min(1).max(40),netPence:z.number().int().nonnegative()}).strict()).min(1),exclusions:z.array(z.string().min(1).max(500)),qualifications:z.array(z.string().min(1).max(500)),subtotalPence:z.number().int().nonnegative(),discountPence:z.number().int().nonnegative(),netPence:z.number().int().nonnegative(),taxPence:z.number().int().nonnegative(),totalPence:z.number().int().nonnegative()}).strict();
export type QuoteDocument=z.infer<typeof quoteDocumentV1>;
export type QuoteApproval={documentVersion:number;contentHash:string;recipients:readonly string[]};

const freeze=<T>(value:T):T=>{if(value&&typeof value==="object"){Object.freeze(value);for(const child of Object.values(value as object))freeze(child);}return value;};
/** Creates a detached, deeply immutable commercial snapshot. */
export function snapshotQuote(raw:unknown):Readonly<QuoteDocument>{return freeze(structuredClone(quoteDocumentV1.parse(raw)));}
export function exactQuoteApprovalMatches(approval:QuoteApproval,artifact:{documentVersion:number;contentHash:string},recipients:readonly string[]):boolean{return approval.documentVersion===artifact.documentVersion&&approval.contentHash===artifact.contentHash&&approval.recipients.length===recipients.length&&approval.recipients.every((value,index)=>value===recipients[index]);}
export const quoteHasZeroPlatformEffects=(_operation:"create"|"download"|"issue"|"send"|"retry",_payload:unknown):Readonly<{feeObligations:0;platformJournals:0;chargeAttempts:0}>=>Object.freeze({feeObligations:0,platformJournals:0,chargeAttempts:0});

const ascii=(value:string)=>value.normalize("NFKD").replace(/[^\x20-\x7e]/gu,"?").replace(/[\\()]/gu,c=>`\\${c}`);
const pounds=(pence:number)=>`GBP ${Math.floor(pence/100)}.${String(pence%100).padStart(2,"0")}`;
const wrap=(text:string,width=84)=>{const words=text.split(/\s+/u);const out:string[]=[];let line="";for(const word of words){if(!line){line=word;continue;}if(`${line} ${word}`.length<=width)line+=` ${word}`;else{out.push(line);line=word;}}if(line)out.push(line);return out;};
export function quotePdfText(document:Readonly<QuoteDocument>):string[]{const d=quoteDocumentV1.parse(document);const rows=["JOBGUARD SYNTHETIC QUOTE",`Quote ${d.reference} | Document version ${d.documentVersion}`,`Issuer: ${d.issuer.name} | ${d.issuer.email}`,...d.issuer.address.map(x=>`Issuer address: ${x}`),`Customer: ${d.customer.name} | ${d.customer.email}`,...d.customer.address.map(x=>`Customer address: ${x}`),"INCLUDED WORK"];d.lines.forEach((line,index)=>rows.push(...wrap(`${index+1}. ${line.description} | ${line.quantity} ${line.unit} | ${pounds(line.netPence)}`)));rows.push("EXCLUSIONS",...(d.exclusions.length?d.exclusions:["None"]),"QUALIFICATIONS",...(d.qualifications.length?d.qualifications:["None"]),`Subtotal ${pounds(d.subtotalPence)}`,`Discount ${pounds(d.discountPence)}`,`Net ${pounds(d.netPence)}`,`VAT ${pounds(d.taxPence)}`,`TOTAL ${pounds(d.totalPence)}`);return rows;}
/** Small deterministic PDF 1.4 writer. Text is paginated at 45 rows and generated only at runtime. */
export function renderQuotePdf(document:Readonly<QuoteDocument>):Uint8Array{const rows=quotePdfText(document).map(ascii),pages=Array.from({length:Math.ceil(rows.length/45)},(_,i)=>rows.slice(i*45,(i+1)*45));const objects:string[]=[];objects[1]="<< /Type /Catalog /Pages 2 0 R >>";const pageIds=pages.map((_,i)=>3+i*2);objects[2]=`<< /Type /Pages /Kids [${pageIds.map(x=>`${x} 0 R`).join(" ")}] /Count ${pages.length} >>`;pages.forEach((lines,i)=>{const pageId=pageIds[i]!,contentId=pageId+1,commands=["BT /F1 10 Tf 48 790 Td 13 TL",...lines.map((line,index)=>`${index?"T* ":""}(${line}) Tj`),"ET"].join("\n");objects[pageId]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${3+pages.length*2} 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${commands.length} >>\nstream\n${commands}\nendstream`;});objects[3+pages.length*2]="<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";let pdf="%PDF-1.4\n",offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`;}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n${offsets.slice(1).map(x=>String(x).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(pdf);}
