/** Provenance never changes the watchdog's lifecycle boundary. */
export function watchdogActive(job: Readonly<{ status: string }>): boolean {
  return job.status === "live";
}

export function watchdogUnavailableCopy(job: Readonly<{ status: string }>): string | null {
  if (watchdogActive(job)) return null;
  return ["invoiced", "paid", "lost"].includes(job.status)
    ? "This job is no longer live."
    : "Switch this job live to use the watchdog — it's free until work starts on site.";
}

export type JobCommandPhase = "pre_live_allowed" | "watchdog_live_only" | "post_live_billing";
/** Exhaustive web mutation registry. Dynamic actions are classified below.
 * New site facts, documents, orders, proof and messages must be live-only. */
export const jobMutationRegistry: Readonly<Record<string, JobCommandPhase>> = {
  "/api/jobs/[id]/commercial-integrity/reviews": "post_live_billing",
  "/api/jobs/[id]/confirm": "pre_live_allowed",
  "/api/jobs/[id]/customer-invoices/[invoiceId]/credit-notes/preview": "post_live_billing",
  "/api/jobs/[id]/customer-invoices/[invoiceId]/credit-notes": "post_live_billing",
  "/api/jobs/[id]/customer-invoices/[invoiceId]/receipts/reversals": "post_live_billing",
  "/api/jobs/[id]/customer-invoices/[invoiceId]/receipts": "post_live_billing",
  "/api/jobs/[id]/customer-invoices": "post_live_billing",
  "/api/jobs/[id]/fee-illustration": "post_live_billing",
  "/api/jobs/[id]/fee-illustration/what-if": "post_live_billing",
  "/api/jobs/[id]/final-account": "post_live_billing",
  "/api/jobs/[id]/materials": "pre_live_allowed",
  // Party setup/corrections and adoption are operational prerequisites, never watchdog inputs.
  "/api/jobs/[id]/parties": "pre_live_allowed",
  "/api/jobs/[id]/parties/import": "pre_live_allowed",
  "/api/jobs/[id]/proof": "watchdog_live_only",
  "/api/jobs/[id]/purchase-orders/placement": "watchdog_live_only",
  "/api/jobs/[id]/purchase-orders/revisions": "watchdog_live_only",
  "/api/jobs/[id]/quotes/acceptance/disposition": "pre_live_allowed",
  "/api/jobs/[id]/quotes/acceptance": "pre_live_allowed",
  "/api/jobs/[id]/quotes/activation": "pre_live_allowed",
  "/api/jobs/[id]/quotes/delivery/[action]": "pre_live_allowed",
  "/api/jobs/[id]/quotes/delivery": "pre_live_allowed",
  "/api/jobs/[id]/quotes/preview": "pre_live_allowed",
  "/api/jobs/[id]/quotes": "pre_live_allowed",
  "/api/jobs/[id]/readiness/[action]": "watchdog_live_only",
  "/api/jobs/[id]/recovery/[action]": "post_live_billing",
  "/api/jobs/[id]/recovery": "post_live_billing",
  "/api/jobs/[id]/recovery-cases/eligibility": "post_live_billing",
  "/api/jobs/[id]/recovery-cases": "post_live_billing",
  "/api/jobs/[id]/relevance-inbox/[action]": "watchdog_live_only",
  "/api/jobs/[id]/relevance-inbox/decisions/[decisionId]": "watchdog_live_only",
  "/api/jobs/[id]/review": "pre_live_allowed",
  "/api/jobs/[id]/supplier-documents/facts/confirm": "watchdog_live_only",
  "/api/jobs/[id]/supplier-documents/intake": "watchdog_live_only",
  "/api/jobs/[id]/supplier-documents/receipts": "watchdog_live_only",
  "/api/jobs/[id]/supplier-matches/corrections": "watchdog_live_only",
  "/api/jobs/[id]/supplier-matches": "watchdog_live_only",
  "/api/jobs/[id]/things-to-check/[action]": "watchdog_live_only",
  "/api/jobs/[id]/variations": "post_live_billing",
  "/api/jobs/capture": "pre_live_allowed",
  "/api/decisions#evaluate": "pre_live_allowed",
  "/api/decisions#resolve": "pre_live_allowed",
  "/api/recovery-cases/[id]/evidence-packs": "post_live_billing",
  "/api/recovery-cases/[id]/evidence-packs/[packId]/attachment-approval": "post_live_billing",
  "/api/jobs/[id]/proof#select_generated": "watchdog_live_only",
  "/api/jobs/[id]/proof#finalize": "watchdog_live_only",
  "/api/jobs/[id]/proof#complete": "watchdog_live_only",
  "/api/jobs/[id]/proof#invalidate": "post_live_billing",
  "/api/jobs/[id]/relevance-inbox/[action]#seed": "watchdog_live_only",
  "/api/jobs/[id]/relevance-inbox/[action]#budget": "pre_live_allowed",

  "method:inbox-relevance-repository.ts#setBudget": "pre_live_allowed",
  "method:proof-repository.ts#invalidate": "post_live_billing",
  "command:confirm_proposal_review": "pre_live_allowed",
  "command:customer_payment.record": "post_live_billing",
  "command:customer_payment.reverse": "post_live_billing",
  "command:finding.resolve": "pre_live_allowed",
  "command:inbox.seed": "watchdog_live_only",
  "command:job.adopt_in_flight": "pre_live_allowed",
  "command:job.switch_live": "pre_live_allowed",
  "command:proof.complete": "watchdog_live_only",
  "command:purchase_order.simulate": "watchdog_live_only",
  "command:quote.acceptance.attest": "pre_live_allowed",
  "command:quote.send": "pre_live_allowed",
  "nest:/decisions/evaluate": "pre_live_allowed",
  "nest:/decisions/resolve": "pre_live_allowed",
  "nest:/jobs/:id/commercial-integrity/reviews": "post_live_billing",
  "nest:/jobs/:id/customer-invoices": "post_live_billing",
  "nest:/jobs/:id/customer-invoices/:invoiceId/credit-notes": "post_live_billing",
  "nest:/jobs/:id/customer-invoices/:invoiceId/credit-notes/preview": "post_live_billing",
  "nest:/jobs/:id/customer-invoices/:invoiceId/receipts": "post_live_billing",
  "nest:/jobs/:id/customer-invoices/:invoiceId/receipts/reversals": "post_live_billing",
  "nest:/jobs/:id/fee-illustration": "post_live_billing",
  "nest:/jobs/:id/fee-illustration/what-if": "post_live_billing",
  "nest:/jobs/:id/final-account": "post_live_billing",
  "nest:/jobs/:id/materials": "pre_live_allowed",
  "nest:/jobs/:id/parties": "pre_live_allowed",
  "nest:/jobs/:id/parties/import": "pre_live_allowed",
  "nest:/jobs/:id/proof": "watchdog_live_only",
  "nest:/jobs/:id/purchase-orders/placement": "watchdog_live_only",
  "nest:/jobs/:id/purchase-orders/revisions": "watchdog_live_only",
  "nest:/jobs/:id/quotes": "pre_live_allowed",
  "nest:/jobs/:id/quotes/preview": "pre_live_allowed",
  "nest:/jobs/:id/quotes/acceptance": "pre_live_allowed",
  "nest:/jobs/:id/quotes/acceptance/disposition": "pre_live_allowed",
  "nest:/jobs/:id/quotes/activation": "pre_live_allowed",
  "nest:/jobs/:id/readiness/advance": "watchdog_live_only",
  "nest:/jobs/:id/readiness/plan": "watchdog_live_only",
  "nest:/jobs/:id/recovery-cases": "post_live_billing",
  "nest:/jobs/:id/recovery-cases/eligibility": "post_live_billing",
  "nest:/jobs/:id/relevance-inbox/:decisionId/dismiss": "watchdog_live_only",
  "nest:/jobs/:id/relevance-inbox/budget": "pre_live_allowed",
  "nest:/jobs/:id/relevance-inbox/seed": "watchdog_live_only",
  "nest:/jobs/:id/supplier-documents/facts/confirm": "watchdog_live_only",
  "nest:/jobs/:id/supplier-documents/intake": "watchdog_live_only",
  "nest:/jobs/:id/supplier-documents/receipts": "watchdog_live_only",
  "nest:/jobs/:id/supplier-matches": "watchdog_live_only",
  "nest:/jobs/:id/supplier-matches/corrections": "watchdog_live_only",
  "nest:/jobs/:id/things-to-check/evaluate": "watchdog_live_only",
  "nest:/jobs/:id/things-to-check/review": "watchdog_live_only",
  "nest:/jobs/:id/things-to-check/supersede-bill": "watchdog_live_only",
  "nest:/jobs/:id/variations": "post_live_billing",
  "nest:/jobs/capture": "pre_live_allowed",
  "nest:/recovery-cases/:id/evidence-packs": "post_live_billing",
  "nest:/recovery-cases/:id/evidence-packs/:packId/attachment-approval": "post_live_billing",
};


/** Business entrypoints used by the registry's live-only commands. */
export const watchdogCommandGuards = [
  { file: "purchase-order-repository.ts", method: "revise", calls: 1 },
  { file: "purchase-order-repository.ts", method: "place", calls: 1 },
  { file: "supplier-document-repository.ts", method: "intake", calls: 1 },
  { file: "supplier-document-repository.ts", method: "appendReceipt", calls: 1 },
  { file: "supplier-document-repository.ts", method: "confirm", calls: 1 },
  { file: "supplier-match-repository.ts", method: "create", calls: 1 },
  { file: "supplier-match-repository.ts", method: "correct", calls: 1 },
  { file: "discrepancy-repository.ts", method: "evaluate", calls: 1 },
  { file: "discrepancy-repository.ts", method: "review", calls: 1 },
  { file: "discrepancy-repository.ts", method: "supersede", calls: 1 },
  { file: "readiness-repository.ts", method: "record", calls: 1 },
  { file: "readiness-repository.ts", method: "advance", calls: 1 },
  { file: "inbox-relevance-repository.ts", method: "seed", calls: 1 },
  { file: "inbox-relevance-repository.ts", method: "dismiss", calls: 1 },
  { file: "evidence.ts", method: "beginUpload", calls: 1 },
  { file: "evidence.ts", method: "finalize", calls: 2 },
  { file: "proof-repository.ts", method: "complete", calls: 2 },
] as const;
