import{expect,test}from"@playwright/test";import{openReview}from"./helpers/capture-journey";test.setTimeout(180_000);const V=async(page:any,id:string,value:string)=>expect.poll(async()=>page.getByTestId(id).textContent(),{timeout:45_000}).toBe(value);
const BANNER="Practice sandbox — synthetic data; nothing is sent or charged";
// C7 asks to "open the job from Jobs". Captured practice jobs are by design NOT listed on the Jobs home (DB test "reads a captured job
// directly without broadening the filtered home list"), so there is no card to click. This is the closest available path: go to Jobs,
// then open the saved job on a fresh navigation (session cookie only) and read the persisted workspace.
async function reopenSavedJob(page:any,jobId:string){await page.goto("/");await expect(page.getByRole("heading",{name:"Jobs",exact:true})).toBeVisible();await page.goto(`/jobs/${jobId}#recovery-cases`);await expect(page.locator("#captured-job-workspace")).toHaveAttribute("data-job-id",jobId);await expect(page.locator("#recovery-cases")).toBeVisible()}
// C7: sandbox banner shown once, and no horizontal page overflow.
async function banner(page:any){await expect(page.getByText(BANNER,{exact:true})).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)}
// C7: a primary action is at least 44x44 CSS px.
async function touchTarget(locator:any){const box=await locator.boundingBox();expect(box).not.toBeNull();expect(box!.width).toBeGreaterThanOrEqual(44);expect(box!.height).toBeGreaterThanOrEqual(44)}
// C7: reach a control with the keyboard alone and require a visible focus indicator on it.
async function keyboardFocus(page:any,locator:any){for(let i=0;i<40;i++){if(await locator.evaluate((el:Element)=>el===document.activeElement))break;await page.keyboard.press("Tab")}await expect(locator).toBeFocused();expect(await locator.evaluate((el:Element)=>{const s=getComputedStyle(el);return s.outlineStyle!=="none"&&parseFloat(s.outlineWidth)>0})).toBe(true)}
const REVIEWER="membership:d1500000-0000-4000-8000-000000000003";
// C1: read the persisted job from a SEPARATE browser context (not another tab of the same context) that carries only the practice-session
// cookie, and prove a context without that cookie is refused. Case/source identity and the saved review are asserted from the server
// response and from the rendered page.
async function secondContextReads(browser:any,context:any,testInfo:any,page:any,jobId:string,expected:{status:string;statusText:string;evidenceRevision:number;policyRevision:number}){
const cookie=(await context.cookies()).filter((c:any)=>c.name==="jg_session");expect(cookie).toHaveLength(1);
const options={viewport:testInfo.project.use.viewport,baseURL:testInfo.project.use.baseURL},path=`/api/jobs/${jobId}/recovery-cases`;
const mine=(await (await page.request.get(path)).json()).cases.at(-1);
const stranger=await browser.newContext(options),second=await browser.newContext({...options,storageState:{cookies:cookie,origins:[]}});
try{
expect((await stranger.request.get(path)).status()).toBe(401);
const saved=(await (await second.request.get(path)).json()).cases.find((c:any)=>c.id===mine.id);
expect(saved).toMatchObject({id:mine.id,jobId,caseType:"withheld_customer_payment",book:"builder_customer",sourceType:"customer_invoice",sourceRefs:["Generated customer invoice INV-18800"],claimedNetPence:32000,landedNetPence:0,revision:mine.revision});
expect(saved.eligibility).toMatchObject({revision:mine.eligibility.revision,status:expected.status,evidenceRevision:expected.evidenceRevision,policyRevision:expected.policyRevision,policyVersion:"reference-d03.v1",reviewerRef:REVIEWER});
const view=await second.newPage();await view.goto(`/jobs/${jobId}#recovery-cases`);
await expect(view.locator("#captured-job-workspace")).toHaveAttribute("data-job-id",jobId);
await V(view,"eligibility-status",expected.statusText);await V(view,"eligibility-reviewer",REVIEWER);await V(view,"case-landed-net","£0.00");await V(view,"case-source-type","Customer invoice");await V(view,"case-book","Builder–customer");
await expect(view.getByText(new RegExp(`evidence revision ${expected.evidenceRevision} · policy reference-d03.v1 revision ${expected.policyRevision}`,"u"))).toBeVisible();
await expect(view.getByRole("link",{name:"Generated customer invoice INV-18800"}).first()).toBeVisible();
}finally{await second.close();await stranger.close()}
}
async function createJob(page:any){await openReview(page);for(const n of["Protect room","Prepare walls","Paint walls","Finish trim","Clean site"])await page.getByRole("button",{name:`Accept ${n}`,exact:true}).click();await page.getByRole("button",{name:"Dismiss Replace shelves",exact:true}).click();await page.getByLabel("Dismissal reason Replace shelves").fill("Not needed");await page.getByLabel(/Answer Confirm disposal/u).fill("Builder removes waste");await page.getByRole("button",{name:"Confirm scope",exact:true}).click()}
test("approves exact cited eligibility without creating landing or fee",async({page,context,browser},testInfo)=>{await createJob(page);const jobId=(await page.locator("#captured-job-workspace").getAttribute("data-job-id"))!;await page.getByRole("button",{name:"Open £320 withheld payment",exact:true}).click();const reviewButton=page.getByRole("button",{name:"Review evidence-backed claim",exact:true}),approveButton=page.getByRole("button",{name:"Approve this eligibility review",exact:true});await touchTarget(reviewButton);await reviewButton.click();await expect(approveButton).toBeEnabled();await touchTarget(approveButton);await reviewButton.focus();await keyboardFocus(page,approveButton);await page.keyboard.press("Enter");await V(page,"claim-eligible-net","£320.00");await V(page,"eligibility-status","Approved for this simulation");await V(page,"case-landed-net","£0.00");await V(page,"case-fee","£0.00");await V(page,"eligibility-reviewer","membership:d1500000-0000-4000-8000-000000000003");await expect(page.getByText(/Case revision 2 · evidence revision 1 · policy reference-d03.v1 revision 1/u)).toBeVisible();await page.reload();await V(page,"eligibility-status","Approved for this simulation");await secondContextReads(browser,context,testInfo,page,jobId,{status:"approved",statusText:"Approved for this simulation",evidenceRevision:1,policyRevision:1});await reopenSavedJob(page,jobId);await V(page,"eligibility-status","Approved for this simulation");await V(page,"claim-eligible-net","£320.00");await V(page,"case-landed-net","£0.00");await V(page,"case-fee","£0.00");await V(page,"eligibility-reviewer","membership:d1500000-0000-4000-8000-000000000003");await banner(page);await page.screenshot({path:`test-results/M4-2-S-${testInfo.project.name}.png`,fullPage:true})});
test("shows every D03 exclusion and keeps posting unavailable",async({page,context,browser},testInfo)=>{await createJob(page);const jobId=(await page.locator("#captured-job-workspace").getAttribute("data-job-id"))!;await page.getByRole("button",{name:"Open £320 withheld payment",exact:true}).click();for(const [button,reason]of[["Review: Pending money","Pending money cannot qualify"],["Review: Manual payment record","A manual payment record is not settlement evidence"],["Review: Prevented spending","Prevented spending is not recovered cash"],["Review: Supplier credit","Supplier credits are excluded by this reference policy"],["Review: Wrong attribution","This payment is not attributed to this recovery case"],["Review: Already allocated","This movement is already allocated"]]as const){await page.getByRole("button",{name:button,exact:true}).click();await expect(page.getByText(reason,{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Approve this eligibility review",exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"Record a landed recovery",exact:true})).toBeDisabled()}for(const button of["Review: Unknown net/tax basis","Review: Unknown causation"]){await page.getByRole("button",{name:button,exact:true}).click();await V(page,"eligibility-status","Non-billable — pending review")}await page.getByRole("button",{name:"Review evidence-backed claim",exact:true}).click();await page.getByRole("button",{name:"Test stale approval after evidence changes",exact:true}).click();await expect(page.getByText("Review the changed evidence before approving",{exact:true})).toBeVisible();await expect(page.locator("#recovery-cases").getByRole("alert")).toBeFocused();await banner(page);await V(page,"case-landed-net","£0.00");
// Bypass the disabled UI with the CURRENT revisions: the server must still require re-review.
const saved=await (await page.request.get(`/api/jobs/${jobId}/recovery-cases`)).json();
const current=saved.cases.at(-1),review=current.eligibility;
const denied=await page.request.post(`/api/jobs/${jobId}/recovery-cases/eligibility`,{data:{version:"recovery-eligibility-command.v1",commandId:crypto.randomUUID(),action:"approve",caseId:current.id,expectedCaseRevision:current.revision,expectedReviewRevision:review.revision,expectedEvidenceRevision:review.evidenceRevision,expectedPolicyRevision:review.policyRevision}});
expect(denied.status()).toBe(409);expect(await denied.json()).toMatchObject({code:"ELIGIBILITY_REVIEW_REQUIRED",message:"Review the changed evidence before approving"});
await page.reload();await V(page,"eligibility-status","Review superseded");
await secondContextReads(browser,context,testInfo,page,jobId,{status:"superseded",statusText:"Review superseded",evidenceRevision:2,policyRevision:1});
const reviewAgain=page.getByRole("button",{name:"Review evidence-backed claim",exact:true}),approveAgain=page.getByRole("button",{name:"Approve this eligibility review",exact:true});await reviewAgain.click();await expect(approveAgain).toBeEnabled();await reviewAgain.focus();await keyboardFocus(page,approveAgain);await page.keyboard.press("Enter");await V(page,"eligibility-status","Approved for this simulation");await V(page,"case-landed-net","£0.00");
// Evidence was superseded to revision 2: the re-review and its approval keep revision 2 (they do not reset to 1).
await expect(page.getByText(/evidence revision 2 · policy reference-d03.v1 revision 1/u)).toBeVisible();
await secondContextReads(browser,context,testInfo,page,jobId,{status:"approved",statusText:"Approved for this simulation",evidenceRevision:2,policyRevision:1});
await reopenSavedJob(page,jobId);await V(page,"eligibility-status","Approved for this simulation");await V(page,"case-landed-net","£0.00");await V(page,"case-fee","£0.00");await banner(page);
});
test("re-reviews and approves at the later policy revision after the policy is superseded",async({page,context,browser},testInfo)=>{await createJob(page);const jobId=(await page.locator("#captured-job-workspace").getAttribute("data-job-id"))!;await page.getByRole("button",{name:"Open £320 withheld payment",exact:true}).click();
const reviewButton=page.getByRole("button",{name:"Review evidence-backed claim",exact:true}),approveButton=page.getByRole("button",{name:"Approve this eligibility review",exact:true}),revisions=/evidence revision 1 · policy reference-d03.v1 revision 2/u;
await reviewButton.click();await V(page,"eligibility-status","Ready for approval");
// The page has no policy-supersession control: supersede through the real route with the CURRENT revisions.
const saved=await (await page.request.get(`/api/jobs/${jobId}/recovery-cases`)).json(),current=saved.cases.at(-1);
const superseded=await page.request.post(`/api/jobs/${jobId}/recovery-cases/eligibility`,{data:{version:"recovery-eligibility-command.v1",commandId:crypto.randomUUID(),action:"supersede",caseId:current.id,expectedCaseRevision:current.revision,subject:"policy"}});expect(superseded.status()).toBe(200);
await page.reload();await V(page,"eligibility-status","Review superseded");await expect(page.getByText(revisions)).toBeVisible();await expect(approveButton).toBeDisabled();await secondContextReads(browser,context,testInfo,page,jobId,{status:"superseded",statusText:"Review superseded",evidenceRevision:1,policyRevision:2});
await reviewButton.click();await V(page,"eligibility-status","Ready for approval");await expect(page.getByText(revisions)).toBeVisible();
await expect(approveButton).toBeEnabled();await approveButton.click();await V(page,"eligibility-status","Approved for this simulation");await expect(page.getByText(revisions)).toBeVisible();await V(page,"case-landed-net","£0.00");await V(page,"case-fee","£0.00");
await secondContextReads(browser,context,testInfo,page,jobId,{status:"approved",statusText:"Approved for this simulation",evidenceRevision:1,policyRevision:2});await banner(page);
});
