import{expect,test,type Page}from"@playwright/test";import{openReview}from"./helpers/capture-journey";
test.setTimeout(180_000);
const B=(page:Page,name:string)=>page.getByRole("button",{name,exact:true});
async function click(page:Page,name:string){const button=B(page,name);await expect(button).toBeVisible();await expect(button).toBeEnabled();await button.click();}
async function quoteV2(page:Page){await openReview(page);for(const name of["Protect room","Prepare walls","Paint walls","Finish trim","Clean site"])await click(page,`Accept ${name}`);await click(page,"Dismiss Replace shelves");await page.getByLabel("Dismissal reason Replace shelves").fill("Not in this practice quote");await page.getByLabel(/Answer Confirm disposal/u).fill("Builder will remove waste");await click(page,"Confirm scope");await click(page,"Price the work");await click(page,"Save draft revision");await expect(page.getByTestId("quote-revision")).toHaveText("1");await page.getByLabel("Unit rate Clean site").fill("200.00");await click(page,"Save draft revision");await expect(page.getByTestId("quote-revision")).toHaveText("2");await click(page,"Preview immutable quote");await click(page,"Simulate sending this quote");await expect(page.getByTestId("quote-delivery")).toHaveText("Queued — not sent");await click(page,"Continue fake worker");await expect(page.getByTestId("quote-delivery")).toHaveText("Simulated delivery — nothing sent");await click(page,"Record practice acceptance");await expect(page.getByTestId("accepted-revision")).toHaveText("Quote 2 · £1,000.00 net");}
async function ids(page:Page){const quote=page.locator(".quote-editor");return{jobId:(await quote.getAttribute("data-job-id"))!,scope:(await quote.getAttribute("data-scope-lineage"))!};}
async function verifyStarted(page:Page,expectedBase:string){await expect(page.getByTestId("job-status")).toHaveText("Work under way");await expect(page.getByTestId("accepted-net")).toHaveText("£1,000.00");await expect(page.getByTestId("recovery-cap")).toHaveText("£15.00");await expect(page.getByTestId("base-status")).toHaveText(expectedBase);await expect(page.getByTestId("base-credit")).toHaveText("£0.00");await expect(page.getByText("Practice only — no real job or payment activated",{exact:true})).toBeVisible();}
test("starts the same practice job once with a frozen no-charge baseline",async({page})=>{await quoteV2(page);const before=await ids(page),path=`/api/jobs/${before.jobId}/quotes/activation`;const payload=()=>({version:"practice-activation-command.v1",commandId:crypto.randomUUID(),scenario:"no_charge"});const [a,b]=await Promise.all([page.request.post(path,{data:payload()}),page.request.post(path,{data:payload()})]);expect([a.status(),b.status()]).toEqual([200,200]);const view=await a.json();expect(view.effects).toMatchObject({activations:1,capSnapshots:1,simulatedObligations:0,settlements:0,realExternalActions:0});await page.reload();await click(page,"Price the work");await verifyStarted(page,"No real charge");expect(await ids(page)).toEqual(before);await expect(page.getByText("Practice sandbox — synthetic data; nothing is sent or charged",{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);const forged=await page.request.post(path,{data:{...payload(),deploymentMode:"production_billing"}});expect(forged.status()).toBe(400);const after=await(await page.request.get(path)).json();expect(after.effects).toMatchObject({activations:1,capSnapshots:1,simulatedObligations:0,settlements:0,platformJournals:0});expect(after.activation).toMatchObject({acceptedNetPence:100000,recoveryCapPence:1500,policyVersion:"reference_fee_policy_v1"});await page.screenshot({path:`test-results/UIWIRE-5-${test.info().project.name}.png`,fullPage:true});});
test("labels the optional isolated base obligation as simulated and unpaid",async({page})=>{await quoteV2(page);await page.getByLabel("Practice activation scenario").selectOption("simulated_base_obligation");await click(page,"Start this practice job");await verifyStarted(page,"Simulated obligation £79.00 — unpaid");await expect(page.getByText("Simulated fee scenario — no payment",{exact:true})).toBeVisible();const before=await ids(page);await page.reload();await click(page,"Price the work");await verifyStarted(page,"Simulated obligation £79.00 — unpaid");expect(await ids(page)).toEqual(before);const view=await(await page.request.get(`/api/jobs/${before.jobId}/quotes/activation`)).json();expect(view.effects).toMatchObject({activations:1,capSnapshots:1,simulatedObligations:1,settlements:0,platformJournals:0,realExternalActions:0});});
test("does not offer activation for an unaccepted quote",async({page})=>{await openReview(page);for(const name of["Protect room","Prepare walls","Paint walls","Finish trim","Clean site"])await click(page,`Accept ${name}`);await click(page,"Dismiss Replace shelves");await page.getByLabel(/Answer Confirm disposal/u).fill("Builder removes waste");await click(page,"Confirm scope");await click(page,"Price the work");await expect(B(page,"Start this practice job")).toHaveCount(0);const {jobId}=await ids(page);const response=await page.request.post(`/api/jobs/${jobId}/quotes/activation`,{data:{version:"practice-activation-command.v1",commandId:crypto.randomUUID(),scenario:"no_charge"}});expect(response.status()).toBe(409);});
