"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
export type DecisionView={id:string;findingId:string;fingerprint:string;jobId:string;jobLabel:string;title:string;detail:string;classification:"mandatory"|"advisory";resolution:"open"|"dismissed";source:{type:string;subjectRef:string;snapshotRevision:number};rule:{id:string;version:string};actionHref:string;authorizedAction:boolean};
type Inbox={version:"decision-inbox.v1";decisions:DecisionView[];counts:{mandatory:number;advisory:number;pending:number}};
export function DecisionInbox({close,tenantId,onCounts}:{close:()=>void;tenantId:string;onCounts:(counts:Inbox["counts"])=>void}) {
 const [view,setView]=useState<Inbox|null>(null),[selected,setSelected]=useState<DecisionView|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{setError("");const response=await fetch(`/api/decisions?tenantId=${encodeURIComponent(tenantId)}`,{cache:"no-store"});if(!response.ok){setError("Decisions could not load");return}const next=await response.json() as Inbox;setView(next);onCounts(next.counts);setSelected(current=>next.decisions.find(x=>x.id===current?.id)??null)},[tenantId,onCounts]);
 useEffect(()=>{void load()},[load]);
 async function dismiss(){if(!selected)return;const response=await fetch("/api/decisions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({version:"decision-resolution-command.v1",commandId:crypto.randomUUID(),tenantId,decisionId:selected.id,findingFingerprint:selected.fingerprint,resolution:"dismissed",expectedSnapshotRevision:selected.source.snapshotRevision})});const result=await response.json() as {label?:string};if(!response.ok){setError("This decision could not be dismissed");return}setMessage(result.label??"");await load()}
 return <section className="decision-page"><button className="back" onClick={close}>← Jobs</button><p className="eyebrow">Deterministic checks · synthetic data</p><h1>Decision Inbox</h1><p>Only decisions produced from this workspace&apos;s persisted job facts. Nothing here sends, orders, creates proof or charges automatically.</p>{error&&<p role="alert" tabIndex={-1}>{error}</p>}<div className="decision-totals"><span>Mandatory <strong data-testid="mandatory-decision-count">{view?.counts.mandatory??0}</strong></span><span>Advisory <strong data-testid="advisory-decision-count">{view?.counts.advisory??0}</strong></span></div><div className="decision-layout"><div className="decision-list" aria-label="Decision list">{view?.decisions.map(item=><button key={item.id} className={selected?.id===item.id?"selected":""} onClick={()=>{setSelected(item);setMessage("")}}><span className={`decision-kind ${item.classification}`}>{item.classification}</span><strong>{item.title}</strong><span>{item.jobLabel} · {item.resolution}</span></button>)}{view&&view.decisions.length===0&&<p>No decisions need attention in this workspace.</p>}</div><article className="decision-detail">{selected?<><span className={`decision-kind ${selected.classification}`}>{selected.classification}</span><h2>{selected.title}</h2><p>{selected.detail}</p><dl className="decision-source"><div><dt>Actual source</dt><dd>{selected.source.type}</dd></div><div><dt>Subject</dt><dd data-testid="decision-source-ref">{selected.source.subjectRef}</dd></div><div><dt>Source revision</dt><dd>{selected.source.snapshotRevision}</dd></div><div><dt>Rule</dt><dd data-testid="decision-rule">{selected.rule.id}</dd></div><div><dt>Rule version</dt><dd data-testid="decision-rule-version">{selected.rule.version}</dd></div><div><dt>Outbound action authorized</dt><dd>{selected.authorizedAction?"Yes":"No"}</dd></div></dl>{selected.classification==="advisory"&&selected.resolution==="open"?<button className="secondary" onClick={()=>void dismiss()}>Dismiss suggestion</button>:selected.classification==="mandatory"?<p className="blocker">Mandatory blockers cannot be suppressed by value, confidence, or advisory budget.</p>:null}<Link className="decision-action" href={selected.actionHref}>Go to required action</Link>{selected.resolution==="dismissed"&&!message&&<p>Dismissed — no action authorized</p>}<p aria-live="polite">{message}</p></>:<><h2>Select a decision</h2><p>Open an item to inspect its persisted source and versioned rule.</p></>}</article></div></section>
}
