BEGIN;
CREATE TABLE app.quote_acceptance (
 id uuid NOT NULL,tenant_id uuid NOT NULL,job_id uuid NOT NULL,document_id uuid NOT NULL,document_version integer NOT NULL CHECK(document_version>0),document_hash char(64) NOT NULL CHECK(document_hash~'^[0-9a-f]{64}$'),accepted_total_pence bigint NOT NULL CHECK(accepted_total_pence>=0),currency char(3) NOT NULL CHECK(currency='GBP'),acceptance_kind varchar(32) NOT NULL CHECK(acceptance_kind='builder_attestation'),actor_membership_id uuid NOT NULL,stated_customer_name varchar(160) NOT NULL,stated_method varchar(20) NOT NULL CHECK(stated_method IN('verbal','email','message','signed-paper')),accepted_at timestamptz NOT NULL,evidence_id uuid,recorded_at timestamptz NOT NULL DEFAULT transaction_timestamp(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,job_id,id),UNIQUE(tenant_id,job_id,document_id),FOREIGN KEY(tenant_id,job_id) REFERENCES app.job(tenant_id,id),FOREIGN KEY(tenant_id,document_id,document_hash) REFERENCES app.quote_document_version(tenant_id,id,content_hash),FOREIGN KEY(tenant_id,actor_membership_id) REFERENCES app.membership(tenant_id,id),FOREIGN KEY(tenant_id,evidence_id) REFERENCES app.evidence_object(tenant_id,id));
CREATE TABLE app.acceptance_event (
 id uuid NOT NULL,tenant_id uuid NOT NULL,job_id uuid NOT NULL,document_id uuid NOT NULL,document_version integer NOT NULL CHECK(document_version>0),document_hash char(64) NOT NULL CHECK(document_hash~'^[0-9a-f]{64}$'),acceptance_id uuid,kind varchar(32) NOT NULL CHECK(kind IN('accepted','declined','superseded','acceptance_cancelled')),actor_membership_id uuid NOT NULL,occurred_at timestamptz NOT NULL,recorded_at timestamptz NOT NULL DEFAULT transaction_timestamp(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,job_id,id),FOREIGN KEY(tenant_id,job_id) REFERENCES app.job(tenant_id,id),FOREIGN KEY(tenant_id,document_id,document_hash) REFERENCES app.quote_document_version(tenant_id,id,content_hash),FOREIGN KEY(tenant_id,job_id,acceptance_id) REFERENCES app.quote_acceptance(tenant_id,job_id,id),FOREIGN KEY(tenant_id,actor_membership_id) REFERENCES app.membership(tenant_id,id),CHECK((kind='accepted' AND acceptance_id IS NOT NULL) OR kind<>'accepted'));

CREATE FUNCTION app.record_builder_attested_acceptance(p_tenant uuid,p_acceptance uuid,p_event uuid,p_job uuid,p_document uuid,p_version integer,p_hash char(64),p_total bigint,p_expected integer,p_actor uuid,p_customer varchar,p_method varchar,p_accepted_at timestamptz,p_evidence uuid) RETURNS app.quote_acceptance LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,app AS $$ DECLARE j app.job;d app.quote_document_version;a app.quote_acceptance;BEGIN
 IF p_tenant IS DISTINCT FROM nullif(current_setting('app.tenant_id',true),'')::uuid THEN RAISE EXCEPTION 'tenant context mismatch' USING ERRCODE='42501';END IF;
 SELECT * INTO j FROM app.job WHERE tenant_id=p_tenant AND id=p_job FOR UPDATE;
 IF NOT FOUND OR j.status<>'quoting' THEN RAISE EXCEPTION 'acceptance is not allowed' USING ERRCODE='22023';END IF;
 IF j.revision<>p_expected THEN RAISE EXCEPTION 'expected revision conflict' USING ERRCODE='40001';END IF;
 SELECT * INTO d FROM app.quote_document_version WHERE tenant_id=p_tenant AND job_id=p_job AND id=p_document;
 IF NOT FOUND OR d.document_version<>p_version OR d.content_hash<>p_hash OR (d.snapshot->>'totalPence')::bigint<>p_total OR NOT EXISTS(SELECT 1 FROM app.quote_send s WHERE s.tenant_id=p_tenant AND s.job_id=p_job AND s.document_id=p_document AND s.content_hash=p_hash) THEN RAISE EXCEPTION 'stale or unissued exact quote' USING ERRCODE='22023';END IF;
 INSERT INTO app.quote_version(id,tenant_id,job_id,version,content_hash,net_value_pence,status) VALUES(p_document,p_tenant,p_job,p_version,p_hash,(d.snapshot->>'netPence')::bigint,'accepted');
 INSERT INTO app.quote_acceptance(id,tenant_id,job_id,document_id,document_version,document_hash,accepted_total_pence,currency,acceptance_kind,actor_membership_id,stated_customer_name,stated_method,accepted_at,evidence_id) VALUES(p_acceptance,p_tenant,p_job,p_document,p_version,p_hash,p_total,'GBP','builder_attestation',p_actor,p_customer,p_method,p_accepted_at,p_evidence) RETURNING * INTO a;
 INSERT INTO app.acceptance_event(id,tenant_id,job_id,document_id,document_version,document_hash,acceptance_id,kind,actor_membership_id,occurred_at) VALUES(p_event,p_tenant,p_job,p_document,p_version,p_hash,p_acceptance,'accepted',p_actor,p_accepted_at);
 UPDATE app.job SET status='accepted',revision=revision+1,accepted_quote_version_id=p_document,updated_at=transaction_timestamp() WHERE tenant_id=p_tenant AND id=p_job;RETURN a;END $$;
CREATE FUNCTION app.record_quote_disposition(p_tenant uuid,p_event uuid,p_job uuid,p_document uuid,p_version integer,p_hash char(64),p_expected integer,p_actor uuid,p_kind varchar,p_occurred timestamptz) RETURNS app.acceptance_event LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,app AS $$ DECLARE j app.job;d app.quote_document_version;a_id uuid;e app.acceptance_event;BEGIN
 IF p_tenant IS DISTINCT FROM nullif(current_setting('app.tenant_id',true),'')::uuid THEN RAISE EXCEPTION 'tenant context mismatch' USING ERRCODE='42501';END IF;
 SELECT * INTO j FROM app.job WHERE tenant_id=p_tenant AND id=p_job FOR UPDATE;IF NOT FOUND OR j.revision<>p_expected THEN RAISE EXCEPTION 'expected revision conflict' USING ERRCODE='40001';END IF;
 SELECT * INTO d FROM app.quote_document_version WHERE tenant_id=p_tenant AND job_id=p_job AND id=p_document AND document_version=p_version AND content_hash=p_hash;IF NOT FOUND THEN RAISE EXCEPTION 'stale exact quote' USING ERRCODE='22023';END IF;
 IF p_kind='declined' AND j.status='quoting' THEN UPDATE app.job SET status='lost',revision=revision+1,updated_at=transaction_timestamp() WHERE tenant_id=p_tenant AND id=p_job;
 ELSIF p_kind='superseded' AND j.status='quoting' THEN NULL;
 ELSIF p_kind='acceptance_cancelled' AND j.status='accepted' AND j.accepted_quote_version_id=p_document THEN SELECT id INTO a_id FROM app.quote_acceptance WHERE tenant_id=p_tenant AND job_id=p_job AND document_id=p_document;UPDATE app.job SET status='quoting',revision=revision+1,accepted_quote_version_id=NULL,updated_at=transaction_timestamp() WHERE tenant_id=p_tenant AND id=p_job;
 ELSE RAISE EXCEPTION 'disposition is not allowed' USING ERRCODE='22023';END IF;
 INSERT INTO app.acceptance_event(id,tenant_id,job_id,document_id,document_version,document_hash,acceptance_id,kind,actor_membership_id,occurred_at) VALUES(p_event,p_tenant,p_job,p_document,p_version,p_hash,a_id,p_kind,p_actor,p_occurred) RETURNING * INTO e;RETURN e;END $$;
CREATE TRIGGER quote_acceptance_immutable BEFORE UPDATE OR DELETE ON app.quote_acceptance FOR EACH ROW EXECUTE FUNCTION app.reject_immutable_authorization_record();
CREATE TRIGGER acceptance_event_immutable BEFORE UPDATE OR DELETE ON app.acceptance_event FOR EACH ROW EXECUTE FUNCTION app.reject_immutable_authorization_record();
DO $$ DECLARE n text;BEGIN FOREACH n IN ARRAY ARRAY['quote_acceptance','acceptance_event'] LOOP EXECUTE format('ALTER TABLE app.%I OWNER TO jobguard_migration',n);EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY',n);EXECUTE format('ALTER TABLE app.%I FORCE ROW LEVEL SECURITY',n);EXECUTE format('CREATE POLICY tenant_isolation ON app.%I FOR ALL TO jobguard_runtime,jobguard_migration USING (tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid) WITH CHECK (tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid)',n);EXECUTE format('GRANT SELECT ON app.%I TO jobguard_runtime',n);EXECUTE format('REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON app.%I FROM jobguard_runtime',n);END LOOP;END $$;
ALTER FUNCTION app.record_builder_attested_acceptance(uuid,uuid,uuid,uuid,uuid,integer,character,bigint,integer,uuid,varchar,varchar,timestamptz,uuid) OWNER TO jobguard_migration;
ALTER FUNCTION app.record_quote_disposition(uuid,uuid,uuid,uuid,integer,character,integer,uuid,varchar,timestamptz) OWNER TO jobguard_migration;
REVOKE ALL ON FUNCTION app.record_builder_attested_acceptance(uuid,uuid,uuid,uuid,uuid,integer,character,bigint,integer,uuid,varchar,varchar,timestamptz,uuid),app.record_quote_disposition(uuid,uuid,uuid,uuid,integer,character,integer,uuid,varchar,timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app.record_builder_attested_acceptance(uuid,uuid,uuid,uuid,uuid,integer,character,bigint,integer,uuid,varchar,varchar,timestamptz,uuid),app.record_quote_disposition(uuid,uuid,uuid,uuid,integer,character,integer,uuid,varchar,timestamptz) TO jobguard_runtime;
COMMIT;
