BEGIN;
CREATE TABLE app.merchant(id uuid NOT NULL,tenant_id uuid NOT NULL,name varchar(160) NOT NULL,created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,id,name),FOREIGN KEY(tenant_id) REFERENCES control_plane.tenant(id));
CREATE TABLE app.merchant_sku(id uuid NOT NULL,tenant_id uuid NOT NULL,merchant_id uuid NOT NULL,sku varchar(100) NOT NULL,description varchar(240) NOT NULL,base_unit varchar(20) NOT NULL CHECK(base_unit IN('each','box','bag','metre','litre')),created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,merchant_id,id),UNIQUE(tenant_id,merchant_id,sku),FOREIGN KEY(tenant_id,merchant_id) REFERENCES app.merchant(tenant_id,id));
CREATE TABLE app.merchant_sku_alias(id uuid NOT NULL,tenant_id uuid NOT NULL,merchant_id uuid NOT NULL,sku_id uuid NOT NULL,alias varchar(160) NOT NULL,created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,merchant_id,alias),FOREIGN KEY(tenant_id,merchant_id) REFERENCES app.merchant(tenant_id,id),FOREIGN KEY(tenant_id,merchant_id,sku_id) REFERENCES app.merchant_sku(tenant_id,merchant_id,id));
CREATE TABLE app.material_pack_conversion(id uuid NOT NULL,tenant_id uuid NOT NULL,sku_id uuid NOT NULL,pack_unit varchar(20) NOT NULL,each_quantity_decimal varchar(40) NOT NULL CHECK(each_quantity_decimal~'^[0-9]+(\.[0-9]{1,6})?$' AND each_quantity_decimal::numeric>0),effective_from date NOT NULL,created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,sku_id,pack_unit,effective_from),FOREIGN KEY(tenant_id,sku_id) REFERENCES app.merchant_sku(tenant_id,id));
CREATE TABLE app.material_requirement(id uuid NOT NULL,tenant_id uuid NOT NULL,job_id uuid NOT NULL,scope_item_id uuid NOT NULL,sku_id uuid NOT NULL,quantity_decimal varchar(40) NOT NULL CHECK(quantity_decimal~'^[0-9]+(\.[0-9]{1,6})?$' AND quantity_decimal::numeric>0),unit varchar(20) NOT NULL,revision integer NOT NULL CHECK(revision>0),created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,job_id,id),UNIQUE(tenant_id,job_id,scope_item_id,revision),FOREIGN KEY(tenant_id,job_id) REFERENCES app.job(tenant_id,id),FOREIGN KEY(tenant_id,job_id,scope_item_id) REFERENCES app.scope_identity(tenant_id,job_id,id),FOREIGN KEY(tenant_id,sku_id) REFERENCES app.merchant_sku(tenant_id,id));
CREATE TABLE app.material_rate_revision(id uuid NOT NULL,tenant_id uuid NOT NULL,merchant_id uuid NOT NULL,sku_id uuid NOT NULL,version integer NOT NULL CHECK(version>0),price_pence bigint NOT NULL CHECK(price_pence>=0 AND price_pence<=1000000000000),currency char(3) NOT NULL CHECK(currency='GBP'),price_unit varchar(20) NOT NULL,tax_basis varchar(10) NOT NULL CHECK(tax_basis IN('net','gross','unknown')),effective_from date NOT NULL,effective_to date,source_label varchar(160) NOT NULL,created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,merchant_id,sku_id,version),FOREIGN KEY(tenant_id,merchant_id) REFERENCES app.merchant(tenant_id,id),FOREIGN KEY(tenant_id,merchant_id,sku_id) REFERENCES app.merchant_sku(tenant_id,merchant_id,id),CHECK(effective_to IS NULL OR effective_to>=effective_from));
DO $$ DECLARE n text;BEGIN FOREACH n IN ARRAY ARRAY['merchant','merchant_sku','merchant_sku_alias','material_pack_conversion','material_requirement','material_rate_revision'] LOOP EXECUTE format('ALTER TABLE app.%I OWNER TO jobguard_migration',n);EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY',n);EXECUTE format('ALTER TABLE app.%I FORCE ROW LEVEL SECURITY',n);EXECUTE format('CREATE POLICY tenant_isolation ON app.%I FOR ALL TO jobguard_runtime,jobguard_migration USING(tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid) WITH CHECK(tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid)',n);EXECUTE format('GRANT SELECT,INSERT ON app.%I TO jobguard_runtime',n);EXECUTE format('REVOKE UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON app.%I FROM jobguard_runtime',n);END LOOP;END$$;
COMMIT;
