BEGIN;
CREATE TABLE app.inbox_finding_revision(
 id uuid NOT NULL,tenant_id uuid NOT NULL,job_id uuid NOT NULL,revision integer NOT NULL CHECK(revision>0),lane text NOT NULL CHECK(lane IN('mandatory','advisory')),rule_id text NOT NULL,rule_revision text NOT NULL,action_type text NOT NULL,recipient_ref text,amount_pence bigint CHECK(amount_pence BETWEEN 0 AND 1000000000000),source_revision text NOT NULL,source_reference text NOT NULL,title text NOT NULL,explanation text NOT NULL,permitted_action text NOT NULL,actor_ref text NOT NULL,subject_ref uuid NOT NULL,payload_hash char(64) NOT NULL,audit_event_id uuid NOT NULL,created_at timestamptz NOT NULL,
 PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,id,revision),UNIQUE(tenant_id,job_id,rule_id,source_reference,revision),FOREIGN KEY(tenant_id,job_id)REFERENCES app.job(tenant_id,id),FOREIGN KEY(tenant_id,audit_event_id)REFERENCES app.audit_event(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE app.inbox_decision_revision(
 id uuid NOT NULL,tenant_id uuid NOT NULL,job_id uuid NOT NULL,revision integer NOT NULL CHECK(revision>0),coalescing_key text NOT NULL,lane text NOT NULL CHECK(lane IN('mandatory','advisory')),rule_id text NOT NULL,rule_revision text NOT NULL,finding_revision integer NOT NULL,source_references jsonb NOT NULL CHECK(jsonb_typeof(source_references)='array'),status text NOT NULL CHECK(status IN('open','dismissed','approved')),actor_ref text NOT NULL,subject_ref uuid NOT NULL,payload_hash char(64) NOT NULL,audit_event_id uuid NOT NULL,created_at timestamptz NOT NULL,
 PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,id,revision),UNIQUE(tenant_id,job_id,coalescing_key,revision),FOREIGN KEY(tenant_id,job_id)REFERENCES app.job(tenant_id,id),FOREIGN KEY(tenant_id,audit_event_id)REFERENCES app.audit_event(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE app.inbox_preference_revision(
 id uuid NOT NULL,tenant_id uuid NOT NULL,membership_id uuid NOT NULL,revision integer NOT NULL CHECK(revision>0),command_id uuid NOT NULL,advisory_budget integer NOT NULL CHECK(advisory_budget BETWEEN 0 AND 100),actor_ref text NOT NULL,subject_ref uuid NOT NULL,payload_hash char(64) NOT NULL,audit_event_id uuid NOT NULL,created_at timestamptz NOT NULL,
 PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,membership_id,revision),UNIQUE(tenant_id,command_id),FOREIGN KEY(tenant_id,membership_id)REFERENCES app.membership(tenant_id,id),FOREIGN KEY(tenant_id,audit_event_id)REFERENCES app.audit_event(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE app.inbox_outcome_event(
 id uuid NOT NULL,tenant_id uuid NOT NULL,job_id uuid NOT NULL,decision_id uuid NOT NULL,decision_revision integer NOT NULL,command_id uuid NOT NULL,event_kind text NOT NULL CHECK(event_kind IN('created','dismissed','approved')),rule_id text NOT NULL,rule_revision text NOT NULL,finding_revision integer NOT NULL,scenario_clock_version text NOT NULL,scenario_at timestamptz NOT NULL,actor_ref text NOT NULL,subject_ref uuid NOT NULL,payload_hash char(64) NOT NULL,audit_event_id uuid NOT NULL,created_at timestamptz NOT NULL,
 PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,command_id),UNIQUE(tenant_id,decision_id,event_kind),FOREIGN KEY(tenant_id,job_id)REFERENCES app.job(tenant_id,id),FOREIGN KEY(tenant_id,decision_id,decision_revision)REFERENCES app.inbox_decision_revision(tenant_id,id,revision),FOREIGN KEY(tenant_id,audit_event_id)REFERENCES app.audit_event(tenant_id,id) DEFERRABLE INITIALLY DEFERRED);
DO $$ DECLARE n text;BEGIN FOREACH n IN ARRAY ARRAY['inbox_decision_revision','inbox_finding_revision','inbox_outcome_event','inbox_preference_revision'] LOOP EXECUTE format('ALTER TABLE app.%I OWNER TO jobguard_migration',n);EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY',n);EXECUTE format('ALTER TABLE app.%I FORCE ROW LEVEL SECURITY',n);EXECUTE format('CREATE POLICY tenant_isolation ON app.%I FOR ALL TO jobguard_runtime,jobguard_migration USING(tenant_id=current_setting(''app.tenant_id'')::uuid) WITH CHECK(tenant_id=current_setting(''app.tenant_id'')::uuid)',n);EXECUTE format('GRANT SELECT,INSERT ON app.%I TO jobguard_runtime',n);EXECUTE format('REVOKE UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON app.%I FROM jobguard_runtime',n);END LOOP;END$$;
COMMIT;
