import { PracticeAccess } from "../practice-access.js";
import { requireLiveJob, WatchdogError } from "@jobguard/db";
import{createHash}from"node:crypto";import{deflateSync}from"node:zlib";import type{Pool}from"pg";import{type TenantTransaction,DEMO_MEMBERSHIP_ID,DEMO_TENANT_ID,EvidenceError,EvidenceService,ProofApplicationRecords,ProofCommandError,ProofCommandService,listConfirmedPracticeScopes,withTenant}from"@jobguard/db";import{z}from"zod";import{proofCommandV1,proofQueryV1}from"./contracts.js";
const requiredType="electrical_certificate",stage="electrical-stage";
function crc32(bytes:Buffer){let crc=0xffffffff;for(const value of bytes){crc^=value;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return(crc^0xffffffff)>>>0}function chunk(type:string,data:Buffer){const name=Buffer.from(type),out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length,0);name.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc32(Buffer.concat([name,data])),8+data.length);return out}export function generatePracticePng(){const header=Buffer.alloc(13);header.writeUInt32BE(2,0);header.writeUInt32BE(2,4);header[8]=8;header[9]=2;const pixels=Buffer.from([0,36,110,64,60,130,74,0,48,120,68,72,145,82]);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk("IHDR",header),chunk("IDAT",deflateSync(pixels)),chunk("IEND",Buffer.alloc(0))])}
type StoredObject={key:string;versionId:string;contentType:string;byteLength:number;bytes:Uint8Array};
class DatabaseSyntheticStorage{private readonly access:PracticeAccess;constructor(private pool:Pool,sessionId?:string){this.access=new PracticeAccess(pool,sessionId)}async createUploadUrl({key}:{key:string}){return`synthetic-db.invalid/${encodeURIComponent(key)}`}async createDownloadUrl({key,versionId}:{key:string;versionId:string}){return`synthetic-db.invalid/${encodeURIComponent(key)}?version=${encodeURIComponent(versionId)}`}async readExactVersion(key:string,versionId:string):Promise<StoredObject>{const practice=await this.access.session();const row=await withTenant(this.pool,practice.context,async db=>(await db.$client.query<{bytes:Buffer;content_type:string}>("SELECT bytes,content_type FROM app.synthetic_evidence_original WHERE tenant_id=$1 AND object_key=$2 AND object_version_id=$3 AND EXISTS(SELECT 1 FROM app.job j WHERE j.tenant_id=app.synthetic_evidence_original.tenant_id AND j.id=app.synthetic_evidence_original.job_id AND j.practice_session_digest=$4)",[DEMO_TENANT_ID,key,versionId,practice.digest])).rows[0]);if(!row)throw new Error("missing original");return{key,versionId,contentType:row.content_type,byteLength:row.bytes.length,bytes:row.bytes}}async deleteExactVersion(){throw new Error("immutable synthetic original")}}
export class ProofApplication{private readonly access:PracticeAccess;private storage;private evidence;private commands;private records;constructor(private pool:Pool,sessionId?:string){this.access=new PracticeAccess(pool,sessionId);this.storage=new DatabaseSyntheticStorage(pool,sessionId);this.evidence=new EvidenceService(pool,this.storage);this.commands=new ProofCommandService(pool,this.storage);this.records=new ProofApplicationRecords(pool)}
 async get(jobIdRaw:unknown){const practice=await this.access.job(jobIdRaw);const parsed=proofQueryV1.safeParse({jobId:jobIdRaw});if(!parsed.success)throw new ProofApplicationError("INVALID_COMMAND");return withTenant(this.pool,practice.context,db=>this.project(db,parsed.data.jobId))}
 /** The proof view of the job as `db` sees it: inside a command's own transaction, the view that command answers with. */
 private async project(db:TenantTransaction,jobId:string){const job=(await db.$client.query("SELECT 1 FROM app.job j WHERE j.tenant_id=$1 AND j.id=$2 ",[DEMO_TENANT_ID,jobId])).rows[0];if(!job)throw new ProofApplicationError("NOT_FOUND");const scope=(await listConfirmedPracticeScopes(db,DEMO_TENANT_ID,jobId,1))[0];if(!scope)throw new ProofApplicationError("NOT_FOUND");const upload=(await db.$client.query<any>(`SELECT u.id,u.state,COALESCE(u.object_version_id,s.object_version_id) object_version_id,e.id evidence_id FROM app.evidence_upload u LEFT JOIN app.synthetic_evidence_original s ON(s.tenant_id,s.upload_id)=(u.tenant_id,u.id) LEFT JOIN app.evidence_object e ON(e.tenant_id,e.upload_id)=(u.tenant_id,u.id) WHERE u.tenant_id=$1 AND u.job_id=$2 AND u.scope_item_id=$3 ORDER BY u.created_at DESC LIMIT 1`,[DEMO_TENANT_ID,jobId,scope.id])).rows[0];const completion=(await db.$client.query<any>(`SELECT s.id,EXISTS(SELECT 1 FROM app.stage_review_event r WHERE (r.tenant_id,r.stage_completion_id)=(s.tenant_id,s.id)) review FROM app.stage_completion s WHERE s.tenant_id=$1 AND s.job_id=$2 AND s.scope_item_id=$3 AND s.stage=$4`,[DEMO_TENANT_ID,jobId,scope.id,stage])).rows[0];const decision=(await db.$client.query<any>(`SELECT d.id FROM app.decision d JOIN app.job_finding f ON(f.tenant_id,f.decision_id)=(d.tenant_id,d.id) WHERE d.tenant_id=$1 AND f.job_id=$2 AND f.subject_ref=$3 ORDER BY f.created_at DESC LIMIT 1`,[DEMO_TENANT_ID,jobId,`${scope.id}:${requiredType}`])).rows[0];return{version:"practice-proof-view.v1",environment:"synthetic_demo",jobId:jobId,scopeItemId:scope.id,requiredEvidenceType:requiredType,upload:upload?{id:upload.id,state:upload.state,objectVersionId:upload.object_version_id,evidenceId:upload.evidence_id}:null,completion:completion?{id:completion.id,reviewRequired:completion.review}:null,decisionId:decision?.id??null,mandatoryDecisionCount:completion&&!completion.review?0:1,realExternalActions:0}}
 /** A live-only proof command is answered once. Its first response is recorded with the request it answered, and a replay returns it as recorded (after re-checking the actor's membership), never a projection rebuilt from today's state or a Decision derived from it. */
 async command(jobId:string,raw:unknown){const practice=await this.access.job(jobId);const parsed=proofCommandV1.safeParse(raw);if(!parsed.success||!proofQueryV1.safeParse({jobId}).success)throw new ProofApplicationError("INVALID_COMMAND");const command=parsed.data;if(command.action==="finalize")await this.access.subject(jobId,"upload",command.uploadId);if(command.action==="invalidate")await this.access.subject(jobId,"evidence",command.evidenceId);if(command.action==="complete")await this.access.subject(jobId,"evidence_or_upload",command.evidenceId);if(command.action==="invalidate")return this.execute(jobId,command,practice);
  const spec={commandId:command.commandId,jobId,action:command.action,requestHash:createHash("sha256").update(JSON.stringify({jobId,...command},Object.keys({jobId,...command}).sort())).digest("hex")};
  const asApplicationError=(error:unknown)=>{
   if((error instanceof ProofCommandError||error instanceof EvidenceError)&&error.code==="COMMAND_CONFLICT")return new WatchdogError("IDEMPOTENCY_CONFLICT");
   if(error instanceof ProofCommandError&&error.code==="FORBIDDEN")return new ProofApplicationError("FORBIDDEN");
   return error;
  };
  const recorded=await this.records.replay(practice.context,{...spec,actorMembershipId:DEMO_MEMBERSHIP_ID}).catch(error=>{throw asApplicationError(error)});if(recorded)return recorded.response as Awaited<ReturnType<ProofApplication["get"]>>;
  // The answer is recorded inside the transaction that completes the command (Codex P2 4197245501), so a failure after the effect
  // commits can no longer leave a completed command without its answer, to be rebuilt later from a job that has since moved on.
  // A command that only replays an earlier effect opens no such transaction; its answer is then recorded first-writer-wins as before.
  const answered:{response?:unknown;recorded?:true}={};
  const completing=async(db:TenantTransaction)=>{answered.response=await this.records.recordIn(db,DEMO_TENANT_ID,{...spec,response:await this.project(db,jobId)});answered.recorded=true};
  const response=await this.execute(jobId,command,practice,completing).catch(error=>{throw asApplicationError(error)});
  if(answered.recorded)return answered.response as Awaited<ReturnType<ProofApplication["get"]>>;
  return await this.records.record(practice.context,{...spec,response}).catch(error=>{throw asApplicationError(error)}) as Awaited<ReturnType<ProofApplication["get"]>>}
 private async execute(jobId:string,command:z.infer<typeof proofCommandV1>,practice:Awaited<ReturnType<PracticeAccess["job"]>>,completing?:(db:TenantTransaction)=>Promise<void>){if(command.action==="select_generated"){const current=await this.get(jobId);if(command.scopeItemId!==current.scopeItemId)throw new ProofApplicationError("NOT_FOUND");const bytes=generatePracticePng(),digest=createHash("sha256").update(bytes).digest("hex");const upload=await this.evidence.beginUpload(practice.context,{id:command.commandId,jobId,scopeItemId:command.scopeItemId,expectedSha256:digest,contentType:"image/png",maximumBytes:bytes.length,retentionClass:"standard_evidence",expiresAt:new Date(Date.now()+3600000)},async(db,upload)=>{const version=`synthetic-${digest.slice(0,16)}`;await db.$client.query(`INSERT INTO app.synthetic_evidence_original(tenant_id,upload_id,job_id,scope_item_id,object_key,object_version_id,environment,content_type,bytes) VALUES($1,$2,$3,$4,$5,$6,'synthetic_demo','image/png',$7) ON CONFLICT(tenant_id,upload_id) DO NOTHING`,[DEMO_TENANT_ID,upload.id,jobId,command.scopeItemId,upload.objectKey,version,bytes]);if(completing)await completing(db);});return this.get(jobId)}if(command.action==="finalize"){await withTenant(this.pool,practice.context,async db=>{await requireLiveJob(db,jobId);const own=(await db.$client.query("SELECT 1 FROM app.evidence_upload WHERE tenant_id=$1 AND job_id=$2 AND id=$3",[DEMO_TENANT_ID,jobId,command.uploadId])).rows[0];if(!own)throw new ProofApplicationError("NOT_FOUND");});try{await this.evidence.finalize(practice.context,{commandId:command.commandId,uploadId:command.uploadId,objectVersionId:command.objectVersionId,evidenceType:requiredType},completing)}catch(error){throw finalizeFailure(error)}return this.get(jobId)}if(command.action==="complete"){const current=await this.get(jobId);if(command.scopeItemId!==current.scopeItemId)throw new ProofApplicationError("NOT_FOUND");try{await this.commands.complete(practice.context,{version:"proof.complete.v1",commandId:command.commandId,actorMembershipId:DEMO_MEMBERSHIP_ID,jobId,scopeItemId:command.scopeItemId,stage,evidenceId:command.evidenceId,requiredEvidenceType:requiredType,decisionId:null,deriveDecision:true},completing)}catch(error){if(error instanceof ProofCommandError){if(error.code==="COMMAND_CONFLICT")throw new WatchdogError("IDEMPOTENCY_CONFLICT");throw new ProofApplicationError(error.code==="FORBIDDEN"?"FORBIDDEN":"PROOF_INVALID");}throw error}return this.get(jobId)}try{await this.commands.invalidate(practice.context,{version:"proof.invalidate.v1",commandId:command.commandId,actorMembershipId:DEMO_MEMBERSHIP_ID,evidenceId:command.evidenceId,reasonCode:command.reasonCode})}catch(error){if(error instanceof WatchdogError)throw error;throw new ProofApplicationError("PROOF_INVALID")}return this.get(jobId)} }
/** How a finalisation failure is answered: watchdog and proof-command refusals pass through, a command id reused with another request is a conflict (409, Codex P2 4197412772), and anything else means the proof is not valid. */
export function finalizeFailure(error:unknown){if((error instanceof EvidenceError||error instanceof ProofCommandError)&&error.code==="COMMAND_CONFLICT")return new WatchdogError("IDEMPOTENCY_CONFLICT");if(error instanceof WatchdogError||error instanceof ProofCommandError)return error;return new ProofApplicationError("PROOF_INVALID")}
export class ProofApplicationError extends Error{constructor(readonly code:"INVALID_COMMAND"|"NOT_FOUND"|"FORBIDDEN"|"PROOF_INVALID"){super(code)}}
