import type { Pool } from "pg";
import { PracticeAccess } from "./practice-access.js";
import{COMMERCIAL_INTEGRITY_DEMO_PROFILE,assertCommercialIntegrityEnvironment,commercialIntegrityDemoFixture,evaluateCommercialIntegrity}from"@jobguard/core";import{integrityReviewV1}from"./commercial-integrity.contracts.js";
export const SCENARIO_NOW=Date.parse("2026-04-09T10:00:00.000Z");
export class CommercialIntegrityApplication{ private readonly access: PracticeAccess; 
 private static readonly feedback:Array<Readonly<{jobId:string;commandId:string;findingKey:string;explanation:string;outcome:"dismissed_false_positive";recordedAt:string}>>=[];
 constructor(private readonly pool: Pool, sessionId?: string, private readonly environment=process.env.JOBGUARD_ENV??"production"){this.access = new PracticeAccess(pool, sessionId);}
 async view(jobId:string){assertCommercialIntegrityEnvironment(this.environment);const practice = await this.access.job(jobId);const result=evaluateCommercialIntegrity(commercialIntegrityDemoFixture(jobId,SCENARIO_NOW),COMMERCIAL_INTEGRITY_DEMO_PROFILE,SCENARIO_NOW);return{version:"commercial-integrity-view.v1",environment:"synthetic_demo",decisionRecord:{id:"D11",status:"proposed",href:"docs/decisions/d11-commercial-integrity-anti-gaming.md",approvalEvidence:null},profile:{...COMMERCIAL_INTEGRITY_DEMO_PROFILE,label:"Example thresholds — not a judgement or billing rule"},evaluatedAt:new Date(SCENARIO_NOW).toISOString(),acceptedCapPence:1200,capBasisPence:80000,findings:result.findings.map((finding,index)=>({...finding,key:`${finding.kind}:${index}`,dismissed:CommercialIntegrityApplication.feedback.some(x=>x.jobId===jobId&&x.findingKey===`${finding.kind}:${index}`)})),feedback:CommercialIntegrityApplication.feedback.filter(x=>x.jobId===jobId)}}
 async review(jobId:string,raw:unknown){assertCommercialIntegrityEnvironment(this.environment);const practice = await this.access.job(jobId);const input=integrityReviewV1.parse(raw),prior=CommercialIntegrityApplication.feedback.find(x=>x.jobId===jobId&&x.commandId===input.commandId);if(prior){if(JSON.stringify(prior)!==JSON.stringify({...prior,commandId:input.commandId,findingKey:input.findingKey,explanation:input.explanation,outcome:input.outcome}))throw new Error("IDEMPOTENCY_CONFLICT");return this.view(jobId)}CommercialIntegrityApplication.feedback.push(Object.freeze({jobId,...input,recordedAt:new Date(SCENARIO_NOW).toISOString()}));return this.view(jobId)}
}
