import { PracticeAccess } from "../practice-access.js";
import { randomUUID } from "node:crypto";
import type { Pool } from "pg";
import { CAPTURE_PROMPT_VERSION, CAPTURE_SCHEMA_VERSION, captureRequestV1 } from "@jobguard/core";
import { extractCaptureFixture,PINNED_CAPTURE_MODEL } from "@jobguard/ai";
import { CaptureRepository,ConfirmProposalReview,DEMO_MEMBERSHIP_ID,DEMO_TENANT_ID,ProposalReviewRepository,UserCommandDispatcher,reviewContentHash} from "@jobguard/db";
import { captureJobStatusV1,reviewConfirmCommandV1,reviewSaveCommandV1,type CaptureWorkspaceResponse } from "./contracts.js";

export class CaptureApplicationError extends Error{constructor(readonly code:"INVALID_CAPTURE"|"TENANT_FORBIDDEN"|"NOT_FOUND"|"REVIEW_REVISION_CONFLICT"|"REVIEW_INCOMPLETE"|"COMMAND_CONFLICT"){super(code)}}
export class CaptureApplication{ private readonly access: PracticeAccess; 
 private captureRepo;private reviewRepo;private dispatcher;
 constructor(pool:Pool, sessionId?: string){this.access = new PracticeAccess(pool, sessionId);this.captureRepo=new CaptureRepository(pool);this.reviewRepo=new ProposalReviewRepository(pool);this.dispatcher=new UserCommandDispatcher(pool)}
 async capture(raw:unknown){const practice = await this.access.session();const parsed=captureRequestV1.safeParse(raw);if(!parsed.success)throw new CaptureApplicationError("INVALID_CAPTURE");if(parsed.data.requested_tenant_id!==DEMO_TENANT_ID)throw new CaptureApplicationError("TENANT_FORBIDDEN");const proposal=await extractCaptureFixture(parsed.data.captureId,parsed.data.source.text,parsed.data.fixtureId);const saved=await this.captureRepo.persist(practice.context,{practiceSessionDigest:practice.digest,captureId:parsed.data.captureId,text:parsed.data.source.text,sourceKind:parsed.data.source.kind,acquisition:parsed.data.source.kind==="browser_local_transcript"?parsed.data.source.acquisition:null,proposal,promptVersion:CAPTURE_PROMPT_VERSION,schemaVersion:CAPTURE_SCHEMA_VERSION,model:PINNED_CAPTURE_MODEL});return this.view(saved.job_id)}
 async view(jobId:string):Promise<CaptureWorkspaceResponse>{const practice = await this.access.job(jobId);const captured=await this.captureRepo.readByJob(practice.context,jobId);if(!captured)throw new CaptureApplicationError("NOT_FOUND");const review=await this.reviewRepo.read(practice.context,jobId);const p=captured.proposal;return{version:1,environment:"synthetic_demo",captureId:captured.capture_id,jobId,proposalId:captured.id,reviewId:review?.reviewId??randomUUID(),source:{text:captured.content_text,version:1,kind:captured.source_kind??"text",acquisition:captured.acquisition_metadata??null,audioByteLength:captured.audio_byte_length??0},proposal:{title:p.title.value,lines:captured.lines.map((x:any)=>{const d=x.proposed_data;const span=d.description.provenance.kind==="extracted"?d.description.provenance.span:null;return{id:x.id,scopeItemId:x.scope_item_id,description:d.description,quantity:d.quantity,unit:d.unit,unitPricePence:d.unitPricePence,room:"Practice job",category:"Work",sourceExcerpt:span?captured.content_text.slice(span.start,span.end):captured.content_text}}),questions:p.questions},review,status:captureJobStatusV1.parse(captured.status)}}
 async save(jobId:string,raw:unknown){const practice = await this.access.job(jobId);const command=reviewSaveCommandV1.safeParse(raw);if(!command.success||command.data.review.jobId!==jobId)throw new CaptureApplicationError("INVALID_CAPTURE");try{await this.reviewRepo.save(practice.context,command.data.review,command.data.expectedRevision);return this.view(jobId)}catch(e){throw this.map(e)}}
 async confirm(jobId:string,raw:unknown){const practice = await this.access.job(jobId);const command=reviewConfirmCommandV1.safeParse(raw);if(!command.success)throw new CaptureApplicationError("INVALID_CAPTURE");const review=await this.reviewRepo.read(practice.context,jobId);if(!review||review.revision!==command.data.expectedRevision)throw new CaptureApplicationError("REVIEW_REVISION_CONFLICT");const cmd={version:"command.v1" as const,commandId:command.data.commandId,commandType:"confirm_proposal_review",semanticKey:`job:${jobId}:confirm:${review.proposalId}`,actorMembershipId:DEMO_MEMBERSHIP_ID,subjectType:"job",subjectRef:jobId,action:{actionType:"confirm_scope",recipient:null,contentHash:reviewContentHash(review),aggregateRevision:review.revision,amountPence:null,currency:null,policyVersion:"synthetic-uiwire-1",expiresAt:new Date(Date.now()+300000)}};try{await this.dispatcher.dispatch(practice.context,cmd,new ConfirmProposalReview(review));return{...(await this.view(jobId)),status:"quoting" as const}}catch(e){throw this.map(e)}}
 private map(e:unknown){const code=(e as {code?:string}).code;if(code==="REVIEW_REVISION_CONFLICT"||code==="REVIEW_INCOMPLETE"||code==="COMMAND_CONFLICT")return new CaptureApplicationError(code);throw e}
}
