"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { contractorRoles, referenceApprovalRulesV1, parsePoundsToPence, approvalRulesV1, contractorWorkspaceV1 } from "@jobguard/core";
import styles from "./contractor-admin.module.css";
// Only unsaved drafts live here; the authoritative view always comes from the application service.
type View={tenantId:string;membershipId:string;revision:number;units:Array<{id:string;name:string;kind:string}>;teams:Array<{id:string;name:string}>;members:Array<{membership_id:string;email:string;revoked:boolean}>;grants:Array<{id:string;membership_id:string;role:string;scope_kind:string;scope_id:string;revoked:boolean}>;clients:Array<{id:string;name:string}>;contracts:Array<{id:string;contract_id:string;revision:number;document:{reference?:string};rule_version_id:string;rules:unknown}>};
export function ContractorAdmin() {
 const [view,setView]=useState<View|null>(null),[busy,setBusy]=useState(false),[stale,setStale]=useState(false),[status,setStatus]=useState("Loading persisted organisation…"),[error,setError]=useState("");
 const [loadErrorVersion,setLoadErrorVersion]=useState(0);
 const errorRef=useRef<HTMLParagraphElement>(null);
 // A practice start supersedes any resume request begun against the old session.
 const readGeneration=useRef(0);
 const [name,setName]=useState("Fictional north"),[parent,setParent]=useState(""),[unitKind,setUnitKind]=useState<"region"|"branch">("region"),[branch,setBranch]=useState(""),[teamName,setTeamName]=useState("Fictional repairs team");
 const [role,setRole]=useState<typeof contractorRoles[number]>("operative"),[scopeKind,setScopeKind]=useState<"tenant"|"region"|"branch"|"team"|"client">("team"),[scopeId,setScopeId]=useState(""),[member,setMember]=useState(""),[fromTeam,setFromTeam]=useState(""),[toTeam,setToTeam]=useState("");
 const [clientName,setClientName]=useState("Fictional housing association"),[clientId,setClientId]=useState(""),[contractId,setContractId]=useState(""),[limit,setLimit]=useState("250.00"),[rules,setRules]=useState(JSON.stringify(referenceApprovalRulesV1,null,2));
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(error)errorRef.current?.focus();},[error,loadErrorVersion]);
 async function fetchJson(url:string,body?:unknown) {const response=await fetch(url,body?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}:{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.code);return result;}
 async function load():Promise<boolean>{const generation=++readGeneration.current;try{const persisted=contractorWorkspaceV1.parse(await fetchJson('/api/contractor'));if(generation!==readGeneration.current)return false;setView(persisted);setStale(false);setError("");setStatus("Persisted organisation loaded");return true;}catch(e){if(generation!==readGeneration.current)return false;setStale(true);if(!view&&(e as Error).message==='UNAUTHENTICATED'){setStatus("Start a generated contractor organisation to practise.");}else{setError("The organisation could not be refreshed. Reload persisted organisation before making another change.");setLoadErrorVersion(v=>v+1);setStatus("Showing an out-of-date organisation. Reload persisted organisation to continue.");}return false;}}
 async function start(){++readGeneration.current;setBusy(true);setError("");try{await fetchJson('/api/session',{});setView(contractorWorkspaceV1.parse(await fetchJson('/api/contractor?action=start',{version:"contractor-practice.v1",environment:"synthetic_demo"})));setStale(false);setStatus("Generated organisation saved");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function command(fields:Record<string,unknown>){if(!view||busy||stale)return;setBusy(true);setError("");setStatus("Saving…");try{await fetchJson('/api/contractor',{version:"contractor-command.v1",environment:"synthetic_demo",commandId:crypto.randomUUID(),expectedRevision:view.revision,id:crypto.randomUUID(),...fields});if(await load())setStatus("Saved to the organisation");else{setStale(true);setError("Saved, but the organisation could not be refreshed. Do not make another change until it reloads.");setStatus("Showing an out-of-date organisation. Reload persisted organisation to continue.");}}catch(e){setStale(true);setError((e as Error).message);setLoadErrorVersion(v=>v+1);setStatus("Change was not confirmed. Reload persisted organisation before trying again.");}finally{setBusy(false);}}
 async function reload(){setBusy(true);try{await load();}finally{setBusy(false);}}
 const locked=busy||stale;
 const allowedScopes=role==='client_approver'?['client']:role==='finance'?['tenant']:['tenant','region','branch','team'];
 const root=view?.tenantId??"",branches=view?.units.filter(x=>x.kind==='branch')??[],regions=view?.units.filter(x=>x.kind==='region')??[];
 const chosenBranch=branch||branches[0]?.id||"",chosenClient=clientId||view?.clients[0]?.id||"";
 const scopeOptions=scopeKind==='tenant'?[{id:root,name:'Whole contractor'}]:scopeKind==='region'?regions:scopeKind==='branch'?branches:scopeKind==='team'?view?.teams??[]:view?.clients??[];
 const selectedScope=scopeId||scopeOptions[0]?.id||"";
 const select=(label:string,value:string,change:(v:string)=>void,options:Array<{id:string;name:string}>)=><label>{label}<select value={value} onChange={e=>change(e.target.value)}><option value="">Choose {label.toLowerCase()}</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
 return <main className={styles.main}><Link href="/">Back to Jobs</Link><h1>Contractor organisation</h1><p>Use the generated fictional contractor and .invalid addresses. Do not enter real people, clients or contracts.</p><p role="status">{status}</p>{error&&<p role="alert" tabIndex={-1} ref={errorRef}>{error}</p>}
 {!view?<button disabled={busy} onClick={()=>void start()}>Start generated contractor practice</button>:<><p data-testid="contractor-tenant">{view.tenantId}</p><p>Track: contractor · operations assigned</p><p>Organisation revision <span data-testid="contractor-revision">{view.revision}</span></p><button disabled={busy} onClick={()=>void reload()}>Reload persisted organisation</button>
 <section><h2>Regions and branches</h2><p>Unsaved draft</p><label>Unit type<select value={unitKind} onChange={e=>{setUnitKind(e.target.value as typeof unitKind);setParent("");}}><option value="region">Region</option><option value="branch">Branch</option></select></label>{select('Parent unit',parent|| (unitKind==='region'?root:regions[0]?.id||""),setParent,unitKind==='region'?[{id:root,name:'Fictional contractor'}]:regions)}<label>Unit name<input value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={locked||!name} onClick={()=>void command({kind:'unit.create',unitKind,parentId:parent||(unitKind==='region'?root:regions[0]?.id),name})}>Add unit</button><ul>{view.units.map(x=><li key={x.id}>{x.kind}: {x.name}</li>)}</ul></section>
 <section><h2>Teams</h2>{select('Branch',chosenBranch,setBranch,branches)}<label>Team name<input value={teamName} onChange={e=>setTeamName(e.target.value)}/></label><button disabled={locked||!chosenBranch} onClick={()=>void command({kind:'team.create',branchId:chosenBranch,name:teamName})}>Add team</button><ul>{view.teams.map(x=><li key={x.id}>{x.name}</li>)}</ul></section>
 <section><h2>Members and scoped grants</h2><p>Invitations create fictional memberships only. Nothing is sent.</p><label>Role<select value={role} onChange={e=>{const v=e.target.value as typeof role;setRole(v);if(v==='client_approver')setScopeKind('client');else if(v==='finance')setScopeKind('tenant');else if(scopeKind==='client')setScopeKind('team');setScopeId("");}}>{contractorRoles.filter(x=>x!=='owner').map(x=><option key={x}>{x}</option>)}</select></label><label>Scope type<select value={scopeKind} onChange={e=>{setScopeKind(e.target.value as typeof scopeKind);setScopeId("");}}>{allowedScopes.map(x=><option key={x}>{x}</option>)}</select></label>{select('Grant scope',selectedScope,setScopeId,scopeOptions)}
 <button disabled={locked||!selectedScope} onClick={()=>void command({kind:'member.invite',role,email:`member-${view.revision}@fictional.invalid`,scope:{kind:scopeKind,id:selectedScope},clientId:role==='client_approver'?selectedScope:null,contractId:null})}>Add fictional member</button>
 {select('Member',member,setMember,view.members.map(x=>({id:x.membership_id,name:x.email})))}<button disabled={locked||!member} onClick={()=>void command({kind:'grant.create',membershipId:member,role,scope:{kind:scopeKind,id:selectedScope},contractId:null})}>Add scoped grant</button><button disabled={locked||!member||member===view.membershipId} onClick={()=>void command({kind:'membership.revoke',membershipId:member})}>Revoke membership</button>
 {select('Previous team',fromTeam,setFromTeam,view.teams)}{select('New team',toTeam,setToTeam,view.teams)}<button disabled={locked||!member||!toTeam||fromTeam===toTeam} onClick={()=>void command({kind:'team.move',membershipId:member,fromTeamId:fromTeam||null,toTeamId:toTeam})}>Move member</button>
 <ul>{view.members.map(x=><li key={x.membership_id}>{x.email} · {x.revoked?'Revoked':'Active'}</li>)}</ul><ul>{view.grants.map(x=><li key={x.id}>{x.role} · {x.scope_kind} · {x.revoked?'Revoked':<button disabled={locked||x.membership_id===view.membershipId} onClick={()=>void command({kind:'grant.revoke',grantId:x.id})}>Revoke {x.role} grant</button>}</li>)}</ul></section>
 <section><h2>Clients and immutable contracts</h2><label>Client name<input value={clientName} onChange={e=>setClientName(e.target.value)}/></label><button disabled={locked} onClick={()=>void command({kind:'client.create',branchId:chosenBranch,name:clientName,clientType:'housing_association'})}>Add fictional client</button><ul>{view.clients.map(x=><li key={x.id}>{x.name}</li>)}</ul>{select('Contract client',chosenClient,setClientId,view.clients)}{select('Existing contract',contractId,setContractId,view.contracts.filter((x,i,a)=>a.findIndex(y=>y.contract_id===x.contract_id)===i).map(x=>({id:x.contract_id,name:x.document.reference??x.contract_id})))}<label>Proceed limit (£)<input inputMode="decimal" value={limit} onChange={e=>setLimit(e.target.value)}/></label><label>Approval rules draft<textarea rows={12} value={rules} onChange={e=>setRules(e.target.value)}/></label><p>Rules are stored as immutable versions. Approval evaluation is a later task.</p><button disabled={locked||!chosenClient} onClick={()=>{try{const document=approvalRulesV1.parse({...JSON.parse(rules),proceedLimit:{pence:parsePoundsToPence(limit),currency:'GBP'}});void command({kind:'contract.revise',clientId:chosenClient,contractId:contractId||crypto.randomUUID(),document:{version:'client-contract.v1',reference:'FICTIONAL-CONTRACT',startsOn:'2026-10-01',endsOn:null,sorVersionIds:[],tenderedAdjustment:{numerator:'-35',denominator:'1000'},photoRule:'required',vatCode:'synthetic-unreviewed',exportedNotBilledAlertDays:30},rules:document});}catch{setError('INVALID_RULE_DOCUMENT');}}}>Save contract version</button><ul>{view.contracts.map(x=><li key={x.id} data-testid="contract-version">{x.document.reference} · version {x.revision}<details><summary>Details and source identity</summary><p>Contract {x.contract_id}</p><p>Version {x.id}</p><p>Rule version {x.rule_version_id}</p><pre>{JSON.stringify(x.rules,null,2)}</pre></details></li>)}</ul></section></>}
 </main>;
}
