import { closeTestPools } from "./pool-test-utils.js";
import { createHash, randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { deflateSync } from "node:zlib";
import EmbeddedPostgres from "embedded-postgres";
import { Pool } from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { PrivateVersionedStorage, StoredObject } from "@jobguard/storage";
import { EvidenceError, EvidenceService, ProofCommandService, migrate, type VerifiedTenantContext, withTenant } from "../src/index.js";

const TENANT="71000000-0000-4000-8000-000000000001", OTHER="71000000-0000-4000-8000-000000000002";
const MEMBER="74000000-0000-4000-8000-000000000001";
const JOB="72000000-0000-4000-8000-000000000001", SCOPE="73000000-0000-4000-8000-000000000001";
const context={tenantId:TENANT} as VerifiedTenantContext, otherContext={tenantId:OTHER} as VerifiedTenantContext;
const hash=(bytes:Uint8Array)=>createHash("sha256").update(bytes).digest("hex");
function validPng(){const crc=(bytes:Buffer)=>{let value=0xffffffff;for(const byte of bytes){value^=byte;for(let i=0;i<8;i++)value=(value>>>1)^((value&1)?0xedb88320:0)}return(value^0xffffffff)>>>0};const chunk=(type:string,data:Buffer)=>{const name=Buffer.from(type),out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);name.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([name,data])),8+data.length);return out};const header=Buffer.alloc(13);header.writeUInt32BE(1,0);header.writeUInt32BE(1,4);header[8]=8;header[9]=2;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk("IHDR",header),chunk("IDAT",deflateSync(Buffer.from([0,20,30,40]))),chunk("IEND",Buffer.alloc(0))])}

class MemoryVersionedStorage implements PrivateVersionedStorage {
  versions=new Map<string,StoredObject>(); deleted:string[]=[];
  put(key:string,versionId:string,bytes:Uint8Array,contentType="image/png"){this.versions.set(`${key}:${versionId}`,{key,versionId,bytes,byteLength:bytes.length,contentType});}
  async createUploadUrl({key,expiresInSeconds}:{key:string;contentType:string;expiresInSeconds:number}){return `memory://put/${key}?expires=${expiresInSeconds}`;}
  async createDownloadUrl({key,versionId,expiresInSeconds}:{key:string;versionId:string;expiresInSeconds:number}){return `memory://get/${key}?version=${versionId}&expires=${expiresInSeconds}`;}
  async readExactVersion(key:string,versionId:string){const value=this.versions.get(`${key}:${versionId}`);if(!value)throw new Error("not found");return value;}
  async deleteExactVersion(key:string,versionId:string){this.deleted.push(`${key}:${versionId}`);this.versions.delete(`${key}:${versionId}`);}
}
let postgres:EmbeddedPostgres,admin:Pool,runtime:Pool,dir:string;const storage=new MemoryVersionedStorage();let service:EvidenceService,proof:ProofCommandService;
beforeAll(async()=>{dir=await mkdtemp(join(tmpdir(),"jobguard-evidence-pg16-"));const port=56500+Math.floor(Math.random()*300);postgres=new EmbeddedPostgres({databaseDir:dir,port,user:"postgres",password:"synthetic-test-only",persistent:false,createPostgresUser:process.getuid?.()===0,initdbFlags:["--lc-messages=C"],onLog:()=>undefined});await postgres.initialise();await postgres.start();admin=new Pool({host:"127.0.0.1",port,database:"postgres",user:"postgres",password:"synthetic-test-only"});await migrate(admin);await admin.query("INSERT INTO control_plane.tenant(id) VALUES($1),($2)",[TENANT,OTHER]);await admin.query("INSERT INTO identity.identity_user(id) VALUES('75000000-0000-4000-8000-000000000001')");await admin.query("INSERT INTO app.account(id,tenant_id,name) VALUES('76000000-0000-4000-8000-000000000001',$1,'Synthetic')",[TENANT]);await admin.query("INSERT INTO app.membership(id,tenant_id,account_id,identity_user_id,role) VALUES($2,$1,'76000000-0000-4000-8000-000000000001','75000000-0000-4000-8000-000000000001','owner')",[TENANT,MEMBER]);await admin.query("INSERT INTO app.job(id,tenant_id,title,status) VALUES($2,$1,'Synthetic stage','live')",[TENANT,JOB]);await admin.query("INSERT INTO app.scope_identity(id,tenant_id,job_id,state) VALUES($3,$1,$2,'confirmed')",[TENANT,JOB,SCOPE]);await admin.query("INSERT INTO app.scope_progress(tenant_id,job_id,scope_item_id,stage) VALUES($1,$2,$3,'in_progress')",[TENANT,JOB,SCOPE]);await admin.query(`CREATE ROLE jobguard_evidence_login LOGIN PASSWORD 'synthetic-runtime-only' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOBYPASSRLS`);await admin.query("GRANT jobguard_runtime TO jobguard_evidence_login");runtime=new Pool({host:"127.0.0.1",port,database:"postgres",user:"jobguard_evidence_login",password:"synthetic-runtime-only"});service=new EvidenceService(runtime,storage);proof=new ProofCommandService(runtime,storage);},60_000);
afterAll(async()=>{await closeTestPools(runtime,admin);await postgres?.stop();await rm(dir,{recursive:true,force:true});});

async function begin(bytes:Uint8Array,overrides:Record<string,unknown>={}){return service.beginUpload(context,{jobId:JOB,scopeItemId:SCOPE,expectedSha256:hash(bytes),contentType:"image/png",maximumBytes:100,expiresAt:new Date(Date.now()+60_000),...overrides});}

describe("verified evidence lifecycle",()=>{
 it("forces RLS and forbids mutation of DB-backed synthetic originals",async()=>{const catalogs=await admin.query(`SELECT relrowsecurity,relforcerowsecurity,pg_get_userbyid(relowner) owner FROM pg_class WHERE oid='app.synthetic_evidence_original'::regclass`);expect(catalogs.rows[0]).toEqual({relrowsecurity:true,relforcerowsecurity:true,owner:"jobguard_migration"});await expect(withTenant(runtime,context,db=>db.$client.query("UPDATE app.synthetic_evidence_original SET bytes=$1 WHERE tenant_id=$2",[Buffer.from([1]),TENANT]))).rejects.toMatchObject({code:"42501"});await expect(withTenant(runtime,context,db=>db.$client.query(`INSERT INTO app.synthetic_evidence_original(tenant_id,upload_id,job_id,scope_item_id,object_key,object_version_id,environment,content_type,bytes) VALUES($1,$2,$3,$4,'x','v','synthetic_demo','image/png',$5)`,[TENANT,randomUUID(),randomUUID(),SCOPE,Buffer.from([1])]))).rejects.toBeTruthy()});
 it("registers one immutable exact version across finalization retries and overwrites",async()=>{const original=validPng();const upload=await begin(original,{deviceCapturedAt:new Date("2026-01-01T00:00:00Z")});storage.put(upload.objectKey,"v1",original);const first=await service.finalize(context,{uploadId:upload.id,objectVersionId:"v1",evidenceType:"site_photo"});storage.put(upload.objectKey,"v2",new Uint8Array([9,9,9]));const second=await service.finalize(context,{uploadId:upload.id,objectVersionId:"v1",evidenceType:"site_photo"});expect(second.id).toBe(first.id);expect(first.object_version_id).toBe("v1");expect(first.sha256.trim()).toBe(hash(original));expect((await storage.readExactVersion(upload.objectKey,"v1")).bytes).toEqual(original);expect(first.device_captured_at).toEqual(new Date("2026-01-01T00:00:00Z"));expect(first.server_received_at).not.toEqual(first.device_captured_at);expect(first.server_verified_at).toBeInstanceOf(Date);const previewBytes=new Uint8Array([3,2,1]);const previewKey=`${upload.objectKey}/preview`;storage.put(previewKey,"pv1",previewBytes);const preview=await service.registerPreview(context,{id:randomUUID(),originalEvidenceId:upload.id,objectKey:previewKey,objectVersionId:"pv1",contentType:"image/png",maximumBytes:10});expect(preview.kind).toBe("preview");expect(preview.original_evidence_id).toBe(upload.id);expect(preview.sha256.trim()).toBe(hash(previewBytes));expect(preview.sha256.trim()).not.toBe(first.sha256.trim());expect(first.object_version_id).toBe("v1");await expect(withTenant(runtime,context,db=>db.$client.query("UPDATE app.evidence_object SET sha256=$1",["0".repeat(64)]))).rejects.toMatchObject({code:"42501"});});
 it.each([{name:"hash",bytes:[1],opts:{expectedSha256:"0".repeat(64)},type:"image/png",max:100,version:"v1",error:"wrong_hash"},{name:"type",bytes:[2],opts:{},type:"image/jpeg",max:100,version:"v1",error:"wrong_type"},{name:"size",bytes:[1,2,3],opts:{maximumBytes:2},type:"image/png",max:2,version:"v1",error:"size_exceeded"},{name:"version",bytes:[4],opts:{},type:"image/png",max:100,version:"missing",error:"missing_version"}])("rejects wrong $name and it cannot prove work",async({bytes,opts,type,version,error})=>{const data=new Uint8Array(bytes);const upload=await begin(data,opts);if(version!=="missing")storage.put(upload.objectKey,version,data,type);await expect(service.finalize(context,{uploadId:upload.id,objectVersionId:version,evidenceType:"site_photo"})).rejects.toThrow(error);await expect(service.linkAndAssertProof(context,{id:randomUUID(),evidenceId:upload.id,jobId:JOB,scopeItemId:SCOPE,requiredEvidenceType:"site_photo"})).rejects.toBeInstanceOf(EvidenceError);});
 it.each([["truncated PNG header",new Uint8Array([137,80,78,71,13,10,26,10])],["corrupt PNG bytes",new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,255])]])("rejects %s after byte/type/hash checks",async(_name,bytes)=>{const upload=await begin(bytes);storage.put(upload.objectKey,"bad-v1",bytes);await expect(service.finalize(context,{uploadId:upload.id,objectVersionId:"bad-v1",evidenceType:"site_photo"})).rejects.toThrow("corrupt_image");});
 it("unfinished, cross-tenant, wrong job/scope/type, and rejected evidence cannot prove work",async()=>{const data=validPng();const pending=await begin(data);await expect(service.linkAndAssertProof(context,{id:randomUUID(),evidenceId:pending.id,jobId:JOB,scopeItemId:SCOPE,requiredEvidenceType:"site_photo"})).rejects.toThrow();storage.put(pending.objectKey,"v1",data);await service.finalize(context,{uploadId:pending.id,objectVersionId:"v1",evidenceType:"site_photo"});for(const candidate of [{ctx:otherContext,job:JOB,scope:SCOPE,type:"site_photo"},{ctx:context,job:randomUUID(),scope:SCOPE,type:"site_photo"},{ctx:context,job:JOB,scope:randomUUID(),type:"site_photo"},{ctx:context,job:JOB,scope:SCOPE,type:"receipt"}])await expect(service.linkAndAssertProof(candidate.ctx,{id:randomUUID(),evidenceId:pending.id,jobId:candidate.job,scopeItemId:candidate.scope,requiredEvidenceType:candidate.type})).rejects.toThrow();});
 it("authorizes exact-version downloads only for the owning tenant and identity",async()=>{const data=validPng();const upload=await begin(data);storage.put(upload.objectKey,"v9",data);await service.finalize(context,{uploadId:upload.id,objectVersionId:"v9",evidenceType:"site_photo"});await expect(service.authorizedDownloadUrl(context,{evidenceId:upload.id,jobId:JOB,scopeItemId:SCOPE,expiresInSeconds:30})).resolves.toContain("version=v9");await expect(service.authorizedDownloadUrl(otherContext,{evidenceId:upload.id,jobId:JOB,scopeItemId:SCOPE,expiresInSeconds:30})).rejects.toThrow("EVIDENCE_NOT_AUTHORIZED");await expect(service.authorizedDownloadUrl(context,{evidenceId:upload.id,jobId:randomUUID(),scopeItemId:SCOPE,expiresInSeconds:30})).rejects.toThrow();});
 it("cleans only expired transient orphan versions",async()=>{const old=new Date(Date.now()-1000);const transient=await begin(new Uint8Array([1]),{expiresAt:old});storage.put(transient.objectKey,"old",new Uint8Array([1]));await withTenant(runtime,context,db=>db.$client.query("UPDATE app.evidence_upload SET state='quarantined',object_version_id='old' WHERE tenant_id=$1 AND id=$2",[TENANT,transient.id]));await begin(new Uint8Array([2]),{expiresAt:old,retentionClass:"standard_evidence"});expect(await service.cleanupExpiredOrphans(context)).toBe(1);expect(storage.deleted).toContain(`${transient.objectKey}:old`);});
 it("gates concurrent completion, audits only identity/hash, and raises rework on invalidation",async()=>{const bytes=validPng();const upload=await begin(bytes);storage.put(upload.objectKey,"proof-v1",bytes);await service.finalize(context,{uploadId:upload.id,objectVersionId:"proof-v1",evidenceType:"completion_photo"});const command={version:"proof.complete.v1" as const,commandId:randomUUID(),actorMembershipId:MEMBER,jobId:JOB,scopeItemId:SCOPE,stage:"completion",evidenceId:upload.id,requiredEvidenceType:"completion_photo",decisionId:null};const [a,b]=await Promise.all([proof.complete(context,command),proof.complete(context,command)]);expect(a).toEqual(b);await withTenant(runtime,context,async db=>{expect((await db.$client.query("SELECT * FROM app.stage_completion")).rows).toHaveLength(1);const audit=(await db.$client.query<{payload:Record<string,unknown>}>("SELECT payload FROM app.audit_event WHERE event_type='proof.completed'")).rows[0]!;expect(JSON.stringify(audit.payload)).toContain(hash(bytes));expect(JSON.stringify(audit.payload)).not.toContain(Buffer.from(bytes).toString("base64"));});await proof.invalidate(context,{version:"proof.invalidate.v1",commandId:randomUUID(),actorMembershipId:MEMBER,evidenceId:upload.id,reasonCode:"object_revoked"});await withTenant(runtime,context,async db=>{expect((await db.$client.query("SELECT event_type FROM app.stage_review_event")).rows).toEqual([{event_type:"proof_rework_required"}]);expect((await db.$client.query("SELECT * FROM app.stage_completion")).rows).toHaveLength(1);});await withTenant(runtime,otherContext,async db=>expect((await db.$client.query("SELECT * FROM app.stage_completion")).rows).toEqual([]));});

});
