import{mkdtemp,rm}from"node:fs/promises";import{tmpdir}from"node:os";import{join}from"node:path";import EmbeddedPostgres from"embedded-postgres";import{Pool}from"pg";import{afterAll,beforeAll,describe,expect,it}from"vitest";import{migrate,type VerifiedTenantContext,withTenant}from"../src/index.js";import{closeTestPools}from"./pool-test-utils.js";
const T="10000000-0000-4000-8000-000000000001",A="20000000-0000-4000-8000-000000000002",U="30000000-0000-4000-8000-000000000003",M="40000000-0000-4000-8000-000000000004",J="50000000-0000-4000-8000-000000000005",S="60000000-0000-4000-8000-000000000006",Q="70000000-0000-4000-8000-000000000007",D="80000000-0000-4000-8000-000000000008",R="90000000-0000-4000-8000-000000000009",H="a".repeat(64),H2="b".repeat(64),context={tenantId:T}as VerifiedTenantContext;let pg:EmbeddedPostgres,admin:Pool,runtime:Pool,dir:string;
beforeAll(async()=>{dir=await mkdtemp(join(tmpdir(),"final-account-pg-"));const port=57800+Math.floor(Math.random()*100);pg=new EmbeddedPostgres({databaseDir:dir,port,user:"postgres",password:"synthetic",persistent:false,createPostgresUser:process.getuid?.()===0,initdbFlags:["--lc-messages=C"],onLog:()=>undefined});await pg.initialise();await pg.start();admin=new Pool({host:"127.0.0.1",port,user:"postgres",password:"synthetic"});await migrate(admin);await admin.query(`INSERT INTO control_plane.tenant(id)VALUES('${T}');INSERT INTO identity.identity_user(id)VALUES('${U}');INSERT INTO app.account(id,tenant_id,name)VALUES('${A}','${T}','Synthetic');INSERT INTO app.membership(id,tenant_id,account_id,identity_user_id,role)VALUES('${M}','${T}','${A}','${U}','owner');INSERT INTO app.job(id,tenant_id,title,status)VALUES('${J}','${T}','Fixture','live');INSERT INTO app.scope_identity(id,tenant_id,job_id,state)VALUES('${S}','${T}','${J}','confirmed');INSERT INTO app.quote_version(id,tenant_id,job_id,version,content_hash,net_value_pence,status)VALUES('${Q}','${T}','${J}',1,'${H}',10000,'accepted');CREATE ROLE final_account_login LOGIN PASSWORD 'synthetic' NOSUPERUSER NOBYPASSRLS;GRANT jobguard_runtime TO final_account_login;`);runtime=new Pool({host:"127.0.0.1",port,database:"postgres",user:"final_account_login",password:"synthetic"});},60000);afterAll(async()=>{await closeTestPools(runtime,admin);await pg.stop();await rm(dir,{recursive:true,force:true})});
describe("final account persistence",()=>{
 it("keeps revisions append-only and same-source rebuild unique",async()=>{
  await withTenant(runtime,context,async db=>{await db.$client.query(`INSERT INTO app.final_account_draft(id,tenant_id,job_id)VALUES($1,$2,$3)`,[D,T,J]);await db.$client.query(`INSERT INTO app.final_account_revision(id,tenant_id,job_id,final_account_draft_id,revision,source_hash,baseline_quote_version_id,currency,tax_policy_version,net_pence,tax_pence,total_pence,issue_blocked,findings)VALUES($1,$2,$3,$4,1,$5,$6,'GBP','candidate_m1_standard_v1',10000,2000,12000,false,'[]')`,[R,T,J,D,H,Q]);});
  await expect(withTenant(runtime,context,db=>db.$client.query(`INSERT INTO app.final_account_revision(id,tenant_id,job_id,final_account_draft_id,revision,source_hash,baseline_quote_version_id,currency,tax_policy_version,net_pence,tax_pence,total_pence,issue_blocked,findings)VALUES(gen_random_uuid(),$1,$2,$3,2,$4,$5,'GBP','candidate_m1_standard_v1',10000,2000,12000,false,'[]')`,[T,J,D,H,Q]))).rejects.toMatchObject({code:"23505"});
  await expect(withTenant(runtime,context,db=>db.$client.query(`UPDATE app.final_account_revision SET total_pence=1`))).rejects.toMatchObject({code:"42501"});
 });
 it("revokes stale issue approval when source content changes and has no invoice or charge effects",async()=>{await admin.query(`INSERT INTO app.decision(id,tenant_id,subject_type,subject_ref,action_type)VALUES(gen_random_uuid(),'${T}','job','${J}','final_account.issue');INSERT INTO app.decision_resolution(id,tenant_id,decision_id,resolution,actor_membership_id)SELECT gen_random_uuid(),'${T}',id,'approved','${M}' FROM app.decision WHERE action_type='final_account.issue';INSERT INTO app.action_authorization(id,tenant_id,decision_id,resolution_id,actor_membership_id,action_type,recipient,content_hash,aggregate_revision,amount_pence,currency,policy_version,expires_at)SELECT gen_random_uuid(),'${T}',d.id,r.id,'${M}','final_account.issue',NULL,'${H}',1,NULL,NULL,'draft.v1',clock_timestamp()+interval '1 day' FROM app.decision d JOIN app.decision_resolution r ON r.decision_id=d.id WHERE d.action_type='final_account.issue'`);await withTenant(runtime,context,db=>db.$client.query(`SELECT app.invalidate_stale_final_account_authorizations($1,$2,$3)`,[T,J,H2]));expect((await admin.query(`SELECT revoked_at IS NOT NULL revoked FROM app.action_authorization WHERE action_type='final_account.issue'`)).rows).toEqual([{revoked:true}]);expect((await admin.query(`SELECT count(*)::int n FROM app.action_outbox`)).rows[0].n).toBe(0);expect((await admin.query(`SELECT count(*)::int n FROM app.journal`)).rows[0].n).toBe(0);});
});
