import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import EmbeddedPostgres from "embedded-postgres";
import { Pool } from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { AdoptInFlightJobMutation, migrate, UserCommandDispatcher, type VerifiedTenantContext, withTenant } from "../src/index.js";
import { closeTestPools } from "./pool-test-utils.js";

const T="10000000-0000-4000-8000-000000000001",OTHER="10000000-0000-4000-8000-000000000002",A="20000000-0000-4000-8000-000000000001",U="30000000-0000-4000-8000-000000000001",M="40000000-0000-4000-8000-000000000001",J="50000000-0000-4000-8000-000000000001",B="60000000-0000-4000-8000-000000000001",H="a".repeat(64);
const context={tenantId:T} as VerifiedTenantContext;
let pg:EmbeddedPostgres,admin:Pool,runtime:Pool,dir:string;
beforeAll(async()=>{dir=await mkdtemp(join(tmpdir(),"import-pg-"));const port=57200+Math.floor(Math.random()*200);pg=new EmbeddedPostgres({databaseDir:dir,port,user:"postgres",password:"synthetic",persistent:false,createPostgresUser:process.getuid?.()===0,initdbFlags:["--lc-messages=C"],onLog:()=>undefined});await pg.initialise();await pg.start();admin=new Pool({host:"127.0.0.1",port,user:"postgres",password:"synthetic"});await migrate(admin);await admin.query(`INSERT INTO control_plane.tenant(id)VALUES('${T}'),('${OTHER}');INSERT INTO identity.identity_user(id)VALUES('${U}');INSERT INTO app.account(id,tenant_id,name)VALUES('${A}','${T}','Synthetic');INSERT INTO app.membership(id,tenant_id,account_id,identity_user_id,role)VALUES('${M}','${T}','${A}','${U}','owner');CREATE ROLE import_login LOGIN PASSWORD 'synthetic' NOSUPERUSER NOBYPASSRLS;GRANT jobguard_runtime TO import_login;`);runtime=new Pool({host:"127.0.0.1",port,database:"postgres",user:"import_login",password:"synthetic",max:3});},60000);
afterAll(async()=>{await closeTestPools(runtime,admin);await pg.stop();await rm(dir,{recursive:true,force:true});});
const input={version:"adopt-job.v1"as const,jobId:J,baselineId:B,title:"Synthetic underway extension",lifecyclePoint:"live"as const,provenance:"imported"as const,lineageStrength:"builder_attested_weaker"as const,baselineHash:H,baselineDescription:"Builder-attested scope already underway",acceptedNetValuePence:100100,recoveryCapPence:1502,acceptedValueSource:"builder_attestation"as const,attestedByMembershipId:M,attestedAt:new Date(0),importTermsVersion:"synthetic_import_terms_candidate.v1"as const,feePolicyVersion:"reference_fee_policy_v1"as const,mode:"synthetic_candidate"as const};
const command={version:"command.v1"as const,commandId:randomUUID(),commandType:"job.adopt_in_flight",semanticKey:`import:${J}`,actorMembershipId:M,subjectType:"job",subjectRef:J,action:{actionType:"job.adopt_in_flight",recipient:null,contentHash:H,aggregateRevision:0,amountPence:100100,currency:"GBP"as const,policyVersion:"synthetic_import_terms_candidate.v1",expiresAt:new Date(Date.now()+60000)}};
describe("in-flight import persistence",()=>{
 it("atomically records imported provenance, attestation, fixed cap and no historic billing",async()=>{const result=await new UserCommandDispatcher(runtime).dispatch(context,command,new AdoptInFlightJobMutation(T,"synthetic_candidate",input));expect(result).toMatchObject({provenance:"imported",lineageStrength:"builder_attested_weaker",billing:"none",historicFeesCreated:0});await withTenant(runtime,context,async db=>{expect((await db.$client.query(`SELECT provenance,accepted_quote_version_id,baseline_quote_version_id,accepted_net_value_pence,recovery_cap_pence FROM app.job WHERE id=$1`,[J])).rows[0]).toEqual({provenance:"imported",accepted_quote_version_id:null,baseline_quote_version_id:null,accepted_net_value_pence:"100100",recovery_cap_pence:"1502"});expect((await db.$client.query(`SELECT provenance,lineage_strength,accepted_value_source,attested_by_membership_id,attested_at FROM app.imported_job_baseline WHERE job_id=$1`,[J])).rows[0]).toMatchObject({provenance:"imported",lineage_strength:"builder_attested_weaker",accepted_value_source:"builder_attestation",attested_by_membership_id:M,attested_at:new Date(0)});for(const table of ["recovery_fee_journal","synthetic_obligation","customer_invoice"]){expect((await db.$client.query(`SELECT count(*)::int n FROM app.${table}`)).rows[0].n).toBe(0);}expect((await db.$client.query(`SELECT actor_ref,payload->'references'->>'attestedAt' attested_at FROM app.audit_event WHERE event_type='job.imported_baseline_attested'`)).rows[0]).toEqual({actor_ref:`membership:${M}`,attested_at:new Date(0).toISOString()});});await expect(withTenant(runtime,context,db=>db.$client.query(`UPDATE app.job SET recovery_cap_pence=999999 WHERE id=$1`,[J]))).rejects.toBeTruthy();await expect(withTenant(runtime,context,db=>db.$client.query(`UPDATE app.imported_job_baseline SET accepted_net_value_pence=999999 WHERE job_id=$1`,[J]))).rejects.toBeTruthy();});
 it("cannot masquerade as quote lineage, cross tenants, or enter production",async()=>{await expect(admin.query(`UPDATE app.job SET accepted_quote_version_id=gen_random_uuid(),baseline_quote_version_id=gen_random_uuid() WHERE tenant_id=$1 AND id=$2`,[T,J])).rejects.toBeTruthy();expect((await withTenant(runtime,{tenantId:OTHER}as VerifiedTenantContext,db=>db.$client.query(`SELECT * FROM app.imported_job_baseline`))).rows).toEqual([]);await expect(new UserCommandDispatcher(runtime).dispatch(context,{...command,commandId:randomUUID(),semanticKey:"production"},new AdoptInFlightJobMutation(T,"production",{...input,jobId:randomUUID(),baselineId:randomUUID()}))).rejects.toThrow("PRODUCTION_IMPORT_DECISION_APPROVAL_REQUIRED");});
});
