import { mkdtemp,rm } from "node:fs/promises";import{tmpdir}from"node:os";import{join}from"node:path";import EmbeddedPostgres from"embedded-postgres";import{Pool}from"pg";import{afterAll,beforeAll,describe,expect,it}from"vitest";import{JobRepository,JobRepositoryError,migrate,type VerifiedTenantContext,withTenant}from"../src/index.js";
const T="10000000-0000-4000-8000-000000000001",J="30000000-0000-4000-8000-000000000003",J2="30000000-0000-4000-8000-000000000004",S="40000000-0000-4000-8000-000000000004",P="50000000-0000-4000-8000-000000000005",Q="60000000-0000-4000-8000-000000000006";const c={tenantId:T}as VerifiedTenantContext;let pg:EmbeddedPostgres,admin:Pool,runtime:Pool,dir:string,repo:JobRepository;
beforeAll(async()=>{dir=await mkdtemp(join(tmpdir(),"jobguard-job-pg16-"));const port=56000+Math.floor(Math.random()*500);pg=new EmbeddedPostgres({databaseDir:dir,port,user:"postgres",password:"test",persistent:false,createPostgresUser:process.getuid?.()===0,initdbFlags:["--lc-messages=C"],onLog:()=>undefined});await pg.initialise();await pg.start();admin=new Pool({host:"127.0.0.1",port,user:"postgres",password:"test"});await migrate(admin);await admin.query(`INSERT INTO control_plane.tenant(id)VALUES('${T}');CREATE ROLE job_test LOGIN PASSWORD 'test' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;GRANT jobguard_runtime TO job_test`);runtime=new Pool({host:"127.0.0.1",port,database:"postgres",user:"job_test",password:"test"});repo=new JobRepository(runtime)},60000);afterAll(async()=>{await runtime?.end();await admin?.end();await pg?.stop();await rm(dir,{recursive:true,force:true})});
describe("job repository and controlled boundaries",()=>{
 it("preserves a reserved ID through proposal review without inventing a price",async()=>{await repo.create(c,["job:update"],{id:J,title:"Kitchen"});const proposal=await repo.reserveProposal(c,["quote:edit"],{id:P,scopeItemId:S,jobId:J,sourceHash:"a".repeat(64),sourceReference:"page:1:0-20"})as any;expect(proposal.scope_item_id).toBe(S);const before=await withTenant(runtime,c,d=>d.$client.query(`SELECT p.scope_item_id,s.state FROM app.proposal_line p JOIN app.scope_identity s USING(tenant_id,job_id) WHERE p.id=$1`,[P]));expect(before.rows[0]).toMatchObject({scope_item_id:S,state:"reserved"});expect((await withTenant(runtime,c,d=>d.$client.query(`SELECT count(*)::int n FROM app.scope_revision`))).rows[0].n).toBe(0);const revision=await repo.confirmProposal(c,["quote:edit"],{proposalId:P,jobId:J,description:"Fit units",quantityDecimal:"1",unit:"item",unitPricePence:100,totalPence:100})as any;expect(revision.scope_item_id).toBe(S)});
 it("rejects same-tenant wrong-job links",async()=>{await repo.create(c,["job:update"],{id:J2,title:"Roof"});await withTenant(runtime,c,d=>d.$client.query(`INSERT INTO app.scope_identity(id,tenant_id,job_id)VALUES('40000000-0000-4000-8000-000000000099',$1,$2)`,[T,J2]));await expect(withTenant(runtime,c,d=>d.$client.query(`INSERT INTO app.scope_lineage(tenant_id,job_id,parent_scope_item_id,child_scope_item_id,kind)VALUES($1,$2,$3,'40000000-0000-4000-8000-000000000099','merge')`,[T,J2,S]))).rejects.toMatchObject({code:"23503"})});
 it("requires expected revisions and rejects illegal lifecycle jumps",async()=>{await expect(repo.transition(c,["job:update"],{jobId:J,expectedRevision:0,to:"live",reason:"switch_live",quoteVersionId:Q,acceptedNetValuePence:100,feePolicyVersion:"reference",recoveryCapPence:10})).rejects.toBeInstanceOf(JobRepositoryError);await repo.transition(c,["job:update"],{jobId:J,expectedRevision:0,to:"quoting",reason:"start_quote"});await expect(repo.transition(c,["job:update"],{jobId:J,expectedRevision:0,to:"lost",reason:"quote_lost"})).rejects.toMatchObject({code:"REVISION_CONFLICT"});await repo.transition(c,["job:update"],{jobId:J,expectedRevision:1,to:"lost",reason:"quote_lost"});await repo.transition(c,["job:update"],{jobId:J,expectedRevision:2,to:"quoting",reason:"reopen_quote"})});
 it("allows progress while frozen commercial records reject direct mutation",async()=>{await repo.transitionProgress(c,["job:update"],{jobId:J,scopeItemId:S,expectedRevision:0,to:"in_progress",reason:"start"});await expect(withTenant(runtime,c,d=>d.$client.query(`UPDATE app.scope_revision SET total_pence=999 WHERE tenant_id=$1`,[T]))).rejects.toMatchObject({code:"42501"});expect((await withTenant(runtime,c,d=>d.$client.query(`SELECT stage FROM app.scope_progress WHERE scope_item_id=$1`,[S]))).rows[0].stage).toBe("in_progress")});
 it("denies generic direct lifecycle and financial-field updates",async()=>{await expect(withTenant(runtime,c,d=>d.$client.query(`UPDATE app.job SET status='live',recovery_cap_pence=1 WHERE id=$1`,[J]))).rejects.toMatchObject({code:"42501"})});
});
