import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { ProposalReview } from "@jobguard/core";
import EmbeddedPostgres from "embedded-postgres";
import { Pool } from "pg";
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it } from "vitest";
import {
  CaptureRepository,
  ConfirmProposalReview,
  migrate,
  ProposalReviewRepository,
  reviewContentHash,
  UserCommandDispatcher,
  type VerifiedTenantContext,
  withTenant,
} from "../src/index.js";
import { closeTestPools } from "./pool-test-utils.js";
const TENANT="10000000-0000-4000-8000-000000000001",ACCOUNT="20000000-0000-4000-8000-000000000002",USER="30000000-0000-4000-8000-000000000003",MEMBER="40000000-0000-4000-8000-000000000004";const context={tenantId:TENANT}as VerifiedTenantContext;let pg:EmbeddedPostgres,admin:Pool,runtime:Pool,dir:string,port:number;
beforeAll(async()=>{dir=await mkdtemp(join(tmpdir(),"review-pg-"));port=56500+Math.floor(Math.random()*300);pg=new EmbeddedPostgres({databaseDir:dir,port,user:"postgres",password:"synthetic-test-only",persistent:false,createPostgresUser:process.getuid?.()===0,initdbFlags:["--lc-messages=C"],onLog:()=>undefined});await pg.initialise();await pg.start();admin=new Pool({host:"127.0.0.1",port,user:"postgres",password:"synthetic-test-only"});await migrate(admin);await admin.query(`INSERT INTO control_plane.tenant(id)VALUES('${TENANT}');INSERT INTO identity.identity_user(id)VALUES('${USER}');INSERT INTO app.account(id,tenant_id,name)VALUES('${ACCOUNT}','${TENANT}','Synthetic');INSERT INTO app.membership(id,tenant_id,account_id,identity_user_id,role)VALUES('${MEMBER}','${TENANT}','${ACCOUNT}','${USER}','owner');CREATE ROLE review_login LOGIN PASSWORD 'synthetic' NOSUPERUSER NOBYPASSRLS;GRANT jobguard_runtime TO review_login;`);},60000);
beforeEach(()=>{runtime=new Pool({host:"127.0.0.1",port,database:"postgres",user:"review_login",password:"synthetic",max:6});});
afterEach(async()=>{
  // Pool.end waits for every checked-out client. Keeping this at test scope makes
  // an un-awaited repository query fail this suite instead of reaching postgres teardown.
  await closeTestPools(runtime);
});
afterAll(async()=>{await closeTestPools(admin);await pg?.stop();await rm(dir,{recursive:true,force:true});});
async function fixture(){const captureId=randomUUID(),source="JOB: Kitchen\nITEM: Fit cabinets";const span={kind:"extracted"as const,span:{sourceId:captureId,sourceVersion:1 as const,start:5,end:12}};const proposal={title:{value:"Kitchen",provenance:span},lines:[{description:{value:"Fit cabinets",provenance:span},quantity:{value:"1",provenance:span},unit:{value:"item",provenance:span},unitPricePence:{value:null,provenance:{kind:"defaulted"as const,note:"price during quote"}}}],materials:[],questions:[{question:{value:"Confirm disposal",provenance:span}}]};const captured=await new CaptureRepository(runtime).persist(context,{captureId,text:source,proposal,promptVersion:"fixture-v1",schemaVersion:"fixture-v1",model:"fixture-only"});const reserved=await withTenant(runtime,context,async db=>(await db.$client.query<{id:string;scope_item_id:string}>(`SELECT id,scope_item_id FROM app.proposal_line WHERE proposal_id=$1`,[captured.id])).rows[0]!);const review:ProposalReview={version:"proposal_review_v1",reviewId:randomUUID(),proposalId:captured.id,jobId:captured.job_id,revision:0,lines:[{id:reserved.id,scopeItemId:reserved.scope_item_id,origin:"proposal",description:"Fit edited cabinets",room:"Kitchen",category:"Joinery",quantity:"1",unit:"item",unitPricePence:null,disposition:"accepted",dismissalReason:null,parentScopeItemIds:[],sourceExcerpt:"Fit cabinets"}],questions:[{id:randomUUID(),question:"Confirm disposal",blocking:false,disposition:"carry_to_quote",answer:null}]};return{review,reserved:reserved.scope_item_id};}
function command(review:ProposalReview,id=randomUUID()){return{version:"command.v1"as const,commandId:id,commandType:"confirm_proposal_review",semanticKey:`job:${review.jobId}:confirm:${review.proposalId}`,actorMembershipId:MEMBER,subjectType:"job",subjectRef:review.jobId,action:{actionType:"confirm_scope",recipient:null,contentHash:reviewContentHash(review),aggregateRevision:review.revision,amountPence:null,currency:null,policyVersion:"synthetic-m1-3",expiresAt:new Date(Date.now()+60_000)}};}
describe("review persistence and confirmation",()=>{it("persists edits, rejects stale saves, preserves reserved identity and confirms once concurrently",async()=>{const{review,reserved}=await fixture();const repo=new ProposalReviewRepository(runtime);const saved=await repo.save(context,review,0);expect(saved.revision).toBe(1);await expect(repo.save(context,{...saved,lines:[{...saved.lines[0]!,description:"stale overwrite"}]},0)).rejects.toMatchObject({code:"REVIEW_REVISION_CONFLICT"});const dispatcher=new UserCommandDispatcher(runtime),raw=command(saved);const [a,b]=await Promise.all([dispatcher.dispatch(context,raw,new ConfirmProposalReview(saved)),dispatcher.dispatch(context,{...raw,commandId:randomUUID()},new ConfirmProposalReview(saved))]);expect(a).toEqual(b);await withTenant(runtime,context,async db=>{expect((await db.$client.query(`SELECT description,unit_price_pence FROM app.scope_revision WHERE scope_item_id=$1`,[reserved])).rows).toEqual([{description:"Fit edited cabinets",unit_price_pence:null}]);expect((await db.$client.query(`SELECT state FROM app.scope_identity WHERE id=$1`,[reserved])).rows[0].state).toBe("confirmed");expect((await db.$client.query(`SELECT status FROM app.job WHERE id=$1`,[review.jobId])).rows[0].status).toBe("quoting");expect(Number((await db.$client.query(`SELECT count(*) n FROM app.command_receipt WHERE semantic_key=$1`,[raw.semanticKey])).rows[0].n)).toBe(1);expect(Number((await db.$client.query(`SELECT count(*) n FROM app.audit_event WHERE subject_ref=$1`,[review.jobId])).rows[0].n)).toBe(1);});});
it("rolls scope, job, audit, authorization and receipt back together",async()=>{const{review}=await fixture();const saved=await new ProposalReviewRepository(runtime).save(context,review,0),raw=command(saved);await expect(new UserCommandDispatcher(runtime).dispatch(context,raw,new ConfirmProposalReview(saved,true))).rejects.toThrow("SYNTHETIC_CONFIRMATION_FAILURE");await withTenant(runtime,context,async db=>{expect((await db.$client.query(`SELECT status FROM app.job WHERE id=$1`,[review.jobId])).rows[0].status).toBe("draft");for(const table of["scope_revision","audit_event","command_receipt","action_authorization"]){expect(Number((await db.$client.query(`SELECT count(*) n FROM app.${table} WHERE tenant_id=$1`,[TENANT])).rows[0].n)).toBeGreaterThanOrEqual(0);}expect(Number((await db.$client.query(`SELECT count(*) n FROM app.command_receipt WHERE semantic_key=$1`,[raw.semanticKey])).rows[0].n)).toBe(0);expect(Number((await db.$client.query(`SELECT count(*) n FROM app.scope_revision WHERE job_id=$1`,[review.jobId])).rows[0].n)).toBe(0);expect(Number((await db.$client.query(`SELECT count(*) n FROM app.audit_event WHERE subject_ref=$1`,[review.jobId])).rows[0].n)).toBe(0);expect(Number((await db.$client.query(`SELECT count(*) n FROM app.decision WHERE subject_ref=$1`,[review.jobId])).rows[0].n)).toBe(0);expect(Number((await db.$client.query(`SELECT count(*) n FROM app.action_authorization WHERE content_hash=$1`,[raw.action.contentHash])).rows[0].n)).toBe(0);});});
it("capture and confirmation create no quote, send, ledger journal or platform collection",async()=>{const{review}=await fixture();const saved=await new ProposalReviewRepository(runtime).save(context,review,0);await new UserCommandDispatcher(runtime).dispatch(context,command(saved),new ConfirmProposalReview(saved));await withTenant(runtime,context,async db=>{for(const table of["quote_revision","quote_document_version","journal","simulated_settlement_event"]){expect(Number((await db.$client.query(`SELECT count(*) n FROM app.${table} WHERE tenant_id=$1`,[TENANT])).rows[0].n)).toBe(0);}});});});
