import { PracticeAccess } from "../practice-access.js";
import type{Pool}from"pg";
import{runJobChecks,applyInitialSuppression,type JobFactSnapshot}from"@jobguard/core";
import { DEMO_TENANT_ID, UserCommandDispatcher, listPracticeFindingScopes, listDecisionInbox, persistFindings, suppressAdvisoryFinding, withTenant } from "@jobguard/db";
import{decisionQueryV1,decisionResolutionWebCommandV1,findingEvaluationCommandV1}from"./contracts.js";

export class DecisionsError extends Error{constructor(readonly code:"FORBIDDEN"|"NOT_FOUND"|"INVALID_COMMAND"|"CONFLICT"){super(code)}}

const view=(rows:any[])=>{const decisions=rows.map(row=>({id:row.decision_id,findingId:row.id,fingerprint:row.fingerprint,jobId:row.job_id,jobLabel:row.job_title,title:row.title,detail:row.detail,classification:row.classification,resolution:row.resolution??"open",source:{type:"Persisted job fact snapshot",subjectRef:row.subject_ref,snapshotRevision:row.snapshot_revision},rule:{id:row.rule_id,version:row.rule_version},actionHref:row.kind==="required_proof"?`/jobs/${row.job_id}#work-proof`:`/jobs/${row.job_id}#materials-review`,authorizedAction:Boolean(row.authorized_action)}));return{version:"decision-inbox.v1" as const,decisions,counts:{mandatory:decisions.filter(x=>x.classification==="mandatory"&&x.resolution==="open").length,advisory:decisions.filter(x=>x.classification==="advisory"&&x.resolution==="open").length,pending:decisions.filter(x=>x.resolution==="open").length}};};
export class DecisionsApplication{ private readonly access: PracticeAccess; constructor(private readonly pool:Pool, sessionId?: string){this.access = new PracticeAccess(pool, sessionId);}
 async list(raw:unknown){const practice = await this.access.command(raw, "list");const parsed=decisionQueryV1.safeParse(raw);if(!parsed.success)throw new DecisionsError("INVALID_COMMAND");const rows=await withTenant(this.pool,practice.context,db=>listDecisionInbox(db,parsed.data.jobId,practice.digest));return view(rows);}
 async evaluate(raw:unknown){const practice = await this.access.command(raw, "evaluate");const parsed=findingEvaluationCommandV1.safeParse(raw);if(!parsed.success)throw new DecisionsError("INVALID_COMMAND");if(parsed.data.tenantId!==DEMO_TENANT_ID)throw new DecisionsError("NOT_FOUND");const result=await withTenant(this.pool,practice.context,async db=>{const job=(await db.$client.query<{revision:number}>("SELECT revision FROM app.job WHERE tenant_id=$1 AND id=$2",[parsed.data.tenantId,parsed.data.jobId])).rows[0];if(!job)throw new DecisionsError("NOT_FOUND");const scopes=await listPracticeFindingScopes(db,parsed.data.tenantId,parsed.data.jobId,2);if(!scopes.length)throw new DecisionsError("CONFLICT");const snapshot:JobFactSnapshot={version:"job-fact-snapshot.v1",tenantId:parsed.data.tenantId,jobId:parsed.data.jobId,revision:job.revision,unresolvedQuestions:[],scopes:[{scopeItemId:scopes[0]!.id,proofRule:"electrical",verifiedProofTypes:["completion_photo"],materialsIncluded:false,valuePence:20000},{scopeItemId:(scopes[1]??scopes[0])!.id,proofRule:null,verifiedProofTypes:[],materialsIncluded:true,valuePence:20000}]};const checks=runJobChecks(snapshot);const filtered=checks.filter(x=>x.subjectRef.endsWith(":electrical_certificate")||x.kind==="materials_bill_review");const selected=applyInitialSuppression(filtered,{minimumAdvisoryValuePence:0,minimumSuggestionConfidence:0,dailyAdvisoryBudget:1},Object.fromEntries(snapshot.scopes.map(x=>[x.scopeItemId,x.valuePence])));const persisted=await persistFindings(db,parsed.data.tenantId,snapshot.revision,selected.visible);for(const hidden of selected.suppressed){await persistFindings(db,parsed.data.tenantId,snapshot.revision,[hidden]);const row=(await listDecisionInbox(db,parsed.data.jobId)).find((x:any)=>x.fingerprint===hidden.fingerprint);if(row)await suppressAdvisoryFinding(db,parsed.data.tenantId,row.id,"daily_advisory_budget","decision-suppression.v1");}return persisted;});return{...await this.list({tenantId:parsed.data.tenantId,jobId:parsed.data.jobId}),evaluation:result};}
 async dismiss(raw:unknown){const practice = await this.access.command(raw, "dismiss");const parsed=decisionResolutionWebCommandV1.safeParse(raw);if(!parsed.success)throw new DecisionsError("INVALID_COMMAND");const membershipId=practice.membershipId;if(!membershipId)throw new DecisionsError("FORBIDDEN");const {tenantId:_,...command}=parsed.data;const result=await new UserCommandDispatcher(this.pool).dismissDecision(practice.context,{...command,semanticKey:`dismiss:${parsed.data.findingFingerprint}`,actorMembershipId:membershipId});return{version:"decision-resolution-result.v1",...result,label:"Dismissed — no action authorized"};}
}
